# Copyright 2023 YOUR ORGANIZATION. All rights reserved.
# 
# YOUR NOTICE

# -----------------------------------------------------------------------------
# File Name 	: xsmp_example_project1/Example/__init__.py
# Generated by 	: PythonGenerator-${qualifiedVersion}
# -----------------------------------------------------------------------------
# This file is auto-generated. Do not edit otherwise your changes will be lost.

import ecss_smp

class M1:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("2386045d-5cff-46b5-b6da-3ff6e2cfd792")

del ecss_smp
