// Copyright 2023-2026 YOUR ORGANIZATION. All rights reserved.
//
// YOUR NOTICE
// -----------------------------------------------------------------------------
// File Name    : xsmp_example_project1.pkg.cpp
// Generated by : XsmpSdkGenerator-2.0.3
// -----------------------------------------------------------------------------
/// @file xsmp_example_project1.pkg.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// -----------------------------------------------------------------------------
// --------------------------------- Includes ----------------------------------
// -----------------------------------------------------------------------------
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <xsmp_example_project1.h>

#if defined(__has_include)
#if __has_include(<Smp/Version.h>)
#include <Smp/Version.h>
#endif
#endif

#ifndef ECSS_SMP_VERSION
#define ECSS_SMP_VERSION 202003L
#endif

#ifdef WIN32
#define DLL_EXPORT                                                             \
  __declspec(dllexport) // %RELAX<mconst> Visual Studio requires a define
#else
#define DLL_EXPORT
#endif

// -----------------------------------------------------------------------------
// -------------------------- Initialise Function ------------------------------
// -----------------------------------------------------------------------------

extern "C" {
/// Global Initialise function of Package xsmp_example_project1.
/// @param simulator Simulator for registration of factories.
/// @param typeRegistry Type Registry for registration of types.
/// @return True if initialisation was successful, false otherwise.
DLL_EXPORT bool Initialise(::Smp::ISimulator *simulator,
                           ::Smp::Publication::ITypeRegistry *typeRegistry) {
  return Initialise_xsmp_example_project1(simulator, typeRegistry);
}
}

// -----------------------------------------------------------------------------
// ---------------------------- Finalise Function ------------------------------
// -----------------------------------------------------------------------------

extern "C" {
/// Global Finalise function of Package xsmp_example_project1.
/// @param simulator Simulator.
/// @return True if finalisation was successful, false otherwise.
DLL_EXPORT bool Finalise(::Smp::ISimulator *simulator) {
#if ECSS_SMP_VERSION >= 202503L
  return Finalise_xsmp_example_project1(simulator);
#else
  static_cast<void>(simulator);
  return Finalise_xsmp_example_project1();
#endif
}
}

// -----------------------------------------------------------------------------
// ------------------------- GetSmpVersion Function ----------------------------
// -----------------------------------------------------------------------------

#if ECSS_SMP_VERSION >= 202503L
extern "C" {
/// Global GetSmpVersion function of Package xsmp_example_project1.
/// The simulator refuses to load a package built against another
/// revision of the standard than its own.
/// @return The revision of the SMP standard this package was built
/// against.
DLL_EXPORT ::Smp::UInt64 GetSmpVersion() {
  return GetSmpVersion_xsmp_example_project1();
}
}
#endif
