// Copyright 2023-2026 YOUR ORGANIZATION. All rights reserved.
//
// YOUR NOTICE
// ---------------------------------------------------------------------------
// File Name    : xsmp_example_project1.h
// Generated by : XsmpSdkGenerator-2.0.3
// ---------------------------------------------------------------------------
/// @file xsmp_example_project1.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_EXAMPLE_PROJECT1_H_
#define XSMP_EXAMPLE_PROJECT1_H_

// ----------------------------------------------------------------------------
// --------------------------------- Includes ---------------------------------
// ----------------------------------------------------------------------------
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>

#if defined(__has_include)
#if __has_include(<Smp/Version.h>)
#include <Smp/Version.h>
#endif
#endif

#ifndef ECSS_SMP_VERSION
#define ECSS_SMP_VERSION 202003L
#endif

// Entry points for static library
extern "C" {
/// Initialise Package xsmp_example_project1.
/// @param simulator Simulator for registration of factories.
/// @param typeRegistry Type Registry for registration of types.
/// @return True if initialisation was successful, false otherwise.
bool Initialise_xsmp_example_project1(
    ::Smp::ISimulator *simulator,
    ::Smp::Publication::ITypeRegistry *typeRegistry);

#if ECSS_SMP_VERSION >= 202503L
/// Finalise Package xsmp_example_project1.
/// @param simulator Simulator to finalise.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_example_project1(::Smp::ISimulator *simulator);

/// Get the revision of the SMP standard Package xsmp_example_project1 was
/// built against.
/// @return The revision of the SMP standard.
::Smp::UInt64 GetSmpVersion_xsmp_example_project1();
#else
/// Finalise Package xsmp_example_project1.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_example_project1();
#endif
}

#endif // XSMP_EXAMPLE_PROJECT1_H_