// Copyright 2023-2024 YOUR ORGANIZATION. All rights reserved.
//
// YOUR NOTICE
// -----------------------------------------------------------------------------
// File Name    : xsmp_example_project1.h
// Generated by : XsmpSdkGenerator-1.1.0
// -----------------------------------------------------------------------------
/// @file xsmp_example_project1.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_EXAMPLE_PROJECT1_H_
#define XSMP_EXAMPLE_PROJECT1_H_

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include <Smp/ISimulator.h>

// ----------------------------------------------------------------------------
// ------------------------ Types and Interfaces ------------------------
// ----------------------------------------------------------------------------

// Entry points for static library
extern "C" {
/// Initialise Package xsmp_example_project1.
/// @param simulator Simulator for registration of factories.
/// @param typeRegistry Type Registry for registration of types.
/// @return True if initialisation was successful, false otherwise.
bool Initialise_xsmp_example_project1(
    ::Smp::ISimulator *simulator,
    ::Smp::Publication::ITypeRegistry *typeRegistry);

/// Finalise Package xsmp_example_project1.
/// @param simulator Optional Simulator.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_example_project1(::Smp::ISimulator *simulator = nullptr);
}

#endif // XSMP_EXAMPLE_PROJECT1_H_
