// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : xsmp_resolver.pkg.cpp
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file xsmp_resolver.pkg.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// -----------------------------------------------------------------------------
// --------------------------------- Includes ----------------------------------
// -----------------------------------------------------------------------------
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <xsmp_resolver.h>

#if defined(__has_include)
#if __has_include(<Smp/Version.h>)
#include <Smp/Version.h>
#endif
#endif

#ifndef ECSS_SMP_VERSION
#define ECSS_SMP_VERSION 202003L
#endif

#ifdef WIN32
#define DLL_EXPORT                                                             \
  __declspec(dllexport) // %RELAX<mconst> Visual Studio requires a define
#else
#define DLL_EXPORT
#endif

// -----------------------------------------------------------------------------
// -------------------------- Initialise Function ------------------------------
// -----------------------------------------------------------------------------

extern "C" {
/// Global Initialise function of Package xsmp_resolver.
/// @param simulator Simulator for registration of factories.
/// @param typeRegistry Type Registry for registration of types.
/// @return True if initialisation was successful, false otherwise.
DLL_EXPORT bool Initialise(::Smp::ISimulator *simulator,
                           ::Smp::Publication::ITypeRegistry *typeRegistry) {
  return Initialise_xsmp_resolver(simulator, typeRegistry);
}
}

// -----------------------------------------------------------------------------
// ---------------------------- Finalise Function ------------------------------
// -----------------------------------------------------------------------------

extern "C" {
/// Global Finalise function of Package xsmp_resolver.
/// @param simulator Simulator.
/// @return True if finalisation was successful, false otherwise.
DLL_EXPORT bool Finalise(::Smp::ISimulator *simulator) {
#if ECSS_SMP_VERSION >= 202503L
  return Finalise_xsmp_resolver(simulator);
#else
  static_cast<void>(simulator);
  return Finalise_xsmp_resolver();
#endif
}
}

// -----------------------------------------------------------------------------
// ------------------------- GetSmpVersion Function ----------------------------
// -----------------------------------------------------------------------------

#if ECSS_SMP_VERSION >= 202503L
extern "C" {
/// Global GetSmpVersion function of Package xsmp_resolver.
/// The simulator refuses to load a package built against another
/// revision of the standard than its own.
/// @return The revision of the SMP standard this package was built
/// against.
DLL_EXPORT ::Smp::UInt64 GetSmpVersion() {
  return GetSmpVersion_xsmp_resolver();
}
}
#endif
