// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ---------------------------------------------------------------------------
// File Name    : xsmp_event_manager.h
// Generated by : XsmpSdkGenerator-2.0.2
// ---------------------------------------------------------------------------
/// @file xsmp_event_manager.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_EVENT_MANAGER_H_
#define XSMP_EVENT_MANAGER_H_

// ----------------------------------------------------------------------------
// --------------------------------- Includes ---------------------------------
// ----------------------------------------------------------------------------
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>

#if defined(__has_include)
#if __has_include(<Smp/Version.h>)
#include <Smp/Version.h>
#endif
#endif

#ifndef ECSS_SMP_VERSION
#define ECSS_SMP_VERSION 202003L
#endif

// Entry points for static library
extern "C" {
/// Initialise Package xsmp_event_manager.
/// @param simulator Simulator for registration of factories.
/// @param typeRegistry Type Registry for registration of types.
/// @return True if initialisation was successful, false otherwise.
bool Initialise_xsmp_event_manager(
    ::Smp::ISimulator *simulator,
    ::Smp::Publication::ITypeRegistry *typeRegistry);

#if ECSS_SMP_VERSION >= 202503L
/// Finalise Package xsmp_event_manager.
/// @param simulator Simulator to finalise.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_event_manager(::Smp::ISimulator *simulator);

/// Get the revision of the SMP standard Package xsmp_event_manager was
/// built against.
/// @return The revision of the SMP standard.
::Smp::UInt64 GetSmpVersion_xsmp_event_manager();
#else
/// Finalise Package xsmp_event_manager.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_event_manager();
#endif
}

#endif // XSMP_EVENT_MANAGER_H_