// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : xsmp_resolver.cpp
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file xsmp_resolver.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Xsmp/Services/XsmpResolver.h>
#include <unordered_set>
#include <xsmp_resolver.h>

// -----------------------------------------------------------------------------
// ----------------------------- Global variables ------------------------------
// -----------------------------------------------------------------------------

namespace {
/// Simulators set.
std::unordered_set<::Smp::ISimulator *> simulators{};
} // namespace

// -----------------------------------------------------------------------------
// --------------------------- Initialise Function -----------------------------
// -----------------------------------------------------------------------------

extern "C" {
/// Initialise Package xsmp_resolver.
/// @param simulator Simulator for registration of factories.
/// @param typeRegistry Type Registry for registration of types.
/// @return True if initialisation was successful, false otherwise.
bool Initialise_xsmp_resolver(
    ::Smp::ISimulator *simulator,
    [[maybe_unused]] ::Smp::Publication::ITypeRegistry *typeRegistry) {
  // check simulator validity
  if (!simulator) {
    return false;
  }
  // avoid double initialisation
  if (!::simulators.emplace(simulator).second) {
    return true;
  }

  // Register Service XsmpResolver
  simulator->AddService(
      new ::Xsmp::Services::XsmpResolver("XsmpResolver", // Name
                                         "",             // Description
                                         simulator,      // Parent
                                         simulator       // Simulator
                                         ));

  return true;
}
}

// ---------------------------------------------------------------------------------
// ---------------------------- Finalise Function ------------------------------
// ---------------------------------------------------------------------------------

extern "C" {
#if ECSS_SMP_VERSION >= 202503L
/// Finalise Package xsmp_resolver.
/// @param simulator Simulator to finalise.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_resolver(::Smp::ISimulator *simulator) {
  // avoid double finalisation of that simulator
  if (::simulators.erase(simulator) == 0) {
    return true;
  }
  return true;
}

/// Get the revision of the SMP standard Package xsmp_resolver was
/// built against.
/// @return The revision of the SMP standard.
::Smp::UInt64 GetSmpVersion_xsmp_resolver() { return ECSS_SMP_VERSION; }
#else
/// Finalise Package xsmp_resolver.
/// @return True if finalisation was successful, false otherwise.
bool Finalise_xsmp_resolver() {
  // avoid double finalisation
  if (::simulators.empty()) {
    return true;
  }
  ::simulators.clear();

  return true;
}
#endif
}
