# Copyright 2023-2026 YOUR ORGANIZATION. All rights reserved.
#
# YOUR NOTICE

# -----------------------------------------------------------------------------
# File Name    : xsmp_example_project1/__init__.py
# Generated by : PythonGenerator-2.0.3
# -----------------------------------------------------------------------------
# This file is auto-generated. Do not edit otherwise your changes will be lost.

from . import Example
