// Copyright 2023 YOUR ORGANIZATION. All rights reserved.
//
// YOUR NOTICE

// -----------------------------------------------------------------------------
// File Name    : Counter.cpp
// Generated by : XsmpSdkGenerator-${qualifiedVersion}
// -----------------------------------------------------------------------------
/// @file Example/Counter.cpp

#include <Example/Counter.h>

namespace Example {
void Counter::DoPublish(::Smp::IPublication *) {}

void Counter::DoConfigure(::Smp::Services::ILogger *,
                          ::Smp::Services::ILinkRegistry *) {}

void Counter::DoConnect(::Smp::ISimulator *) {}

void Counter::DoDisconnect() {}

void Counter::_IncrementCount() { ++count; }
void Counter::ResetCount() { count = 0; }
void Counter::_Add(::Smp::IObject *, ::Smp::Int32 value) { count += value; }
} // namespace Example
