# Copyright 2023-2024 THALES ALENIA SPACE FRANCE. All rights reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -----------------------------------------------------------------------------
# File Name 	: xsmp_scheduler/Xsmp/Services/__init__.py
# Generated by 	: PythonGenerator-1.1.0
# -----------------------------------------------------------------------------
# This file is auto-generated. Do not edit otherwise your changes will be lost.

import ecss_smp

class XsmpScheduler:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("98df2ec3-7f94-4a49-8c95-3da0b3525ae5")

del ecss_smp
