// Copyright 2023 THALES ALENIA SPACE FRANCE. All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// -----------------------------------------------------------------------------
// File Name    : ModelWithOperations.cpp
// Generated by : XsmpSdkGenerator-${qualifiedVersion}
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/ModelWithOperations.cpp

#include <Xsmp/Tests/ModelWithOperations.h>

namespace Xsmp {
namespace Tests {
void ModelWithOperations::DoPublish(::Smp::IPublication*) {
}

void ModelWithOperations::DoConfigure(::Smp::Services::ILogger*,
        ::Smp::Services::ILinkRegistry*) {
}

void ModelWithOperations::DoConnect(::Smp::ISimulator*) {
}

void ModelWithOperations::DoDisconnect() {
}

void ModelWithOperations::voidOperation() {
}
::Smp::Bool ModelWithOperations::boolOperation() {
    ::Smp::Bool ret { };
    return ret;
}
::Smp::Char8 ModelWithOperations::char8Operation() {
    ::Smp::Char8 ret { };
    return ret;
}
::Smp::DateTime ModelWithOperations::dateTimeOperation() {
    ::Smp::DateTime ret { };
    return ret;
}
::Smp::Duration ModelWithOperations::durationOperation() {
    ::Smp::Duration ret { };
    return ret;
}
::Smp::Float32 ModelWithOperations::float32Operation() {
    ::Smp::Float32 ret { };
    return ret;
}
::Smp::Float64 ModelWithOperations::float64Operation() {
    ::Smp::Float64 ret { };
    return ret;
}
::Smp::Int16 ModelWithOperations::int16Operation() {
    ::Smp::Int16 ret { };
    return ret;
}
::Smp::Int32 ModelWithOperations::int32Operation() {
    ::Smp::Int32 ret { };
    return ret;
}
::Smp::Int64 ModelWithOperations::int64Operation() {
    ::Smp::Int64 ret { };
    return ret;
}
::Smp::Int8 ModelWithOperations::int8Operation() {
    ::Smp::Int8 ret { };
    return ret;
}
::Smp::String8 ModelWithOperations::string8Operation() {
    ::Smp::String8 ret { };
    return ret;
}
::Smp::UInt16 ModelWithOperations::uint16Operation() {
    ::Smp::UInt16 ret { };
    return ret;
}
::Smp::UInt32 ModelWithOperations::uint32Operation() {
    ::Smp::UInt32 ret { };
    return ret;
}
::Smp::UInt64 ModelWithOperations::uint64Operation() {
    ::Smp::UInt64 ret { };
    return ret;
}
::Smp::UInt8 ModelWithOperations::uint8Operation() {
    ::Smp::UInt8 ret { };
    return ret;
}
} // namespace Tests
} // namespace Xsmp
