// Copyright 2023-2026 YOUR ORGANIZATION. All rights reserved.
//
// YOUR NOTICE
// -----------------------------------------------------------------------------
// File Name    : CounterManagerGen.cpp
// Generated by : XsmpSdkGenerator-2.0.3
// -----------------------------------------------------------------------------
/// @file Example/CounterManagerGen.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Example/CounterManager.h>
#include <Smp/ViewKind.h>
#include <Xsmp/ComponentHelper.h>
#include <Xsmp/Request.h>
#include <string>

#if defined(__has_include)
#if __has_include(<Smp/Version.h>)
#include <Smp/Version.h>
#endif
#endif

#ifndef ECSS_SMP_VERSION
#define ECSS_SMP_VERSION 202003L
#endif

namespace Example {
//--------------------------- Constructor -------------------------
CounterManagerGen::CounterManagerGen(::Smp::String8 name,
                                     ::Smp::String8 description,
                                     ::Smp::IComposite *parent,
                                     ::Smp::ISimulator *simulator)
    : // Base class
      ::Xsmp::Model(name, description, parent, simulator),
      // Container counters
      counters{
          "counters",                 // Name
          "list of handled counters", // Description
          this,                       // Parent
          0,                          // Lower bound
          -1                          // Upper bound
      } {}

void CounterManagerGen::Publish(::Smp::IPublication *receiver) {
  // Call parent class implementation first
  ::Xsmp::Model::Publish(receiver);

  // Publish Property sum
  receiver->PublishProperty("sum",                           // Name
                            "sum of all contained counters", // Description
                            ::Smp::Uuids::Uuid_Int32,        // Type UUID
                            ::Smp::AccessKind::AK_ReadOnly,  // Access Kind
                            ::Smp::ViewKind::VK_All          // View Kind
  );
  // Publish Property average
  receiver->PublishProperty("average",                           // Name
                            "average of all contained counters", // Description
                            ::Smp::Uuids::Uuid_Float64,          // Type UUID
                            ::Smp::AccessKind::AK_ReadOnly,      // Access Kind
                            ::Smp::ViewKind::VK_All              // View Kind
  );
  // Publish Property count
  receiver->PublishProperty("count",                         // Name
                            "set all counter value",         // Description
                            ::Smp::Uuids::Uuid_Int32,        // Type UUID
                            ::Smp::AccessKind::AK_WriteOnly, // Access Kind
                            ::Smp::ViewKind::VK_All          // View Kind
  );
  // Call user DoPublish if any
  ::Xsmp::Component::Helper::Publish<::Example::CounterManager>(this, receiver);
}

void CounterManagerGen::Configure(
    ::Smp::Services::ILogger *logger,
    ::Smp::Services::ILinkRegistry *linkRegistry) {
  // Call parent implementation first
  ::Xsmp::Model::Configure(logger, linkRegistry);

  // Call user DoConfigure if any
  ::Xsmp::Component::Helper::Configure<::Example::CounterManager>(this, logger,
                                                                  linkRegistry);
}

void CounterManagerGen::Connect(::Smp::ISimulator *simulator) {
  // Call parent implementation first
  ::Xsmp::Model::Connect(simulator);

  // Call user DoConnect if any
  ::Xsmp::Component::Helper::Connect<::Example::CounterManager>(this,
                                                                simulator);
}

void CounterManagerGen::Disconnect() {
  if (this->::Xsmp::Component::GetState() ==
      ::Smp::ComponentStateKind::CSK_Connected) {
    // Call user DoDisconnect if any
    ::Xsmp::Component::Helper::Disconnect<::Example::CounterManager>(this);
  }

  // Call parent implementation last, to remove references to the Simulator and
  // its services
  ::Xsmp::Model::Disconnect();
}

std::map<std::string_view,
         std::function<void(CounterManagerGen *, ::Smp::IRequest *)>>
    CounterManagerGen::_requestHandlers{

        // Getter handler for Property sum
        {"get_sum",
         [](CounterManagerGen *component, ::Smp::IRequest *request) {
           ::Xsmp::Request::setReturnValue(request,
                                           ::Smp::PrimitiveTypeKind::PTK_Int32,
                                           component->get_sum());
         }},

        // Getter handler for Property average
        {"get_average",
         [](CounterManagerGen *component, ::Smp::IRequest *request) {
           ::Xsmp::Request::setReturnValue(
               request, ::Smp::PrimitiveTypeKind::PTK_Float64,
               component->get_average());
         }},

        // Setter handler for Property count
        {"set_count",
         [](CounterManagerGen *component, ::Smp::IRequest *request) {
           component->set_count(::Xsmp::Request::get<::Smp::Int32>(
               component, request, "count",
               ::Smp::PrimitiveTypeKind::PTK_Int32));
         }},

    };

void CounterManagerGen::Invoke(::Smp::IRequest *request) {
  if (!request) {
    return;
  }
#if ECSS_SMP_VERSION >= 202503L
  // the request carries the bare property name and tells a getter
  // from a setter apart through its type
  const std::string key =
      (request->GetType() == ::Smp::RequestType::RT_Get   ? "get_"
       : request->GetType() == ::Smp::RequestType::RT_Set ? "set_"
                                                          : "") +
      std::string{request->GetName()};
#else
  // the request already names the property accessor
  const std::string_view key{request->GetOperationName()};
#endif
  if (auto it = _requestHandlers.find(key); it != _requestHandlers.end()) {
    it->second(this, request);
  } else {
    // pass the request down to the base class
    ::Xsmp::Model::Invoke(request);
  }
}

const ::Smp::Uuid &CounterManagerGen::GetUuid() const {
  return Uuid_CounterManager;
}

} // namespace Example