// Copyright 2023-2026 YOUR ORGANIZATION. All rights reserved.
//
// YOUR NOTICE
// -----------------------------------------------------------------------------
// File Name    : CounterGen.h
// Generated by : XsmpSdkGenerator-2.0.3
// -----------------------------------------------------------------------------
/// @file Example/CounterGen.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef EXAMPLE_COUNTERGEN_H_
#define EXAMPLE_COUNTERGEN_H_

// ----------------------------------------------------------------------------
// --------------------------- Forward Declarations ---------------------------
// ----------------------------------------------------------------------------

namespace Example {
class Counter;
} // namespace Example

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/IComposite.h>
#include <Smp/IRequest.h>
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <Xsmp/EntryPoint.h>
#include <Xsmp/EntryPointPublisher.h>
#include <Xsmp/EventConsumer.h>
#include <Xsmp/EventSink.h>
#include <Xsmp/Model.h>
#include <functional>
#include <map>
#include <string_view>

// ----------------------------------------------------------------------------
// --------------------------- Types and Interfaces ---------------------------
// ----------------------------------------------------------------------------

namespace Example {
/// Universally unique identifier of type Counter.
inline constexpr ::Smp::Uuid Uuid_Counter{0x2386045dU, 0x5cffU, 0x46b5U,
                                          0xb6daU, 0x3ff6e2cfd792U};

class CounterGen : public ::Xsmp::Model,
                   public virtual ::Xsmp::EventConsumer,
                   public virtual ::Xsmp::EntryPointPublisher {
  friend class ::Example::Counter;

public:
  /// Constructor setting name, description, parent and simulator.
  /// @param name Name of new Model instance.
  /// @param description Description of new Model instance.
  /// @param parent Parent of new Model instance.
  /// @param simulator The simulator instance.
  CounterGen(::Smp::String8 name, ::Smp::String8 description,
             ::Smp::IComposite *parent, ::Smp::ISimulator *simulator);
  /// deleted copy constructor
  CounterGen(const CounterGen &) = delete;
  /// deleted move constructor
  CounterGen(CounterGen &&) = delete;
  /// deleted copy assignment
  CounterGen &operator=(const CounterGen &) = delete;
  /// deleted move assignment
  CounterGen &operator=(CounterGen &&) = delete;

  /// Virtual destructor to release memory.
  ~CounterGen() override = default;

  /// Request the Model to publish its fields, properties and
  /// operations against the provided publication receiver.
  /// @param   receiver Publication receiver.
  /// @throws  Smp::InvalidComponentState
  void Publish(::Smp::IPublication *receiver) override;

  /// Request the Model to perform any custom configuration. The
  /// component can create and configure other components using the field
  /// values of its published fields.
  /// @param   logger Logger service for logging of error messages during
  ///          configuration.
  /// @param   linkRegistry Reference to the link registry services, so
  ///          that the Model can register links that it creates
  ///          during configuration.
  /// @throws  Smp::InvalidComponentState
  void Configure(::Smp::Services::ILogger *logger,
                 ::Smp::Services::ILinkRegistry *linkRegistry) override;

  /// Allow the Model to connect to the simulator and its simulation
  /// services.
  /// @param   simulator Simulation Environment that hosts the Model.
  /// @throws  Smp::InvalidComponentState
  void Connect(::Smp::ISimulator *simulator) override;

  /// Ask the Model to disconnect from the simulator and all its
  /// simulation services.
  /// @throws  Smp::InvalidComponentState
  void Disconnect() override;

  /// Get Universally Unique Identifier of the Model.
  /// @return  Universally Unique Identifier of the Model.
  const ::Smp::Uuid &GetUuid() const override;

private:
  static std::map<std::string_view,
                  std::function<void(CounterGen *, ::Smp::IRequest *)>>
      _requestHandlers;

public:
  /// Dynamically invoke an operation using a request object that has
  /// been created and filled with parameter values by the caller.
  /// @param   request Request object to invoke.
  /// @throws  Smp::InvalidOperationName
  /// @throws  Smp::InvalidParameterCount
  /// @throws  Smp::InvalidParameterType
  void Invoke(::Smp::IRequest *request) override;

private:
  virtual void ResetCount() = 0;

public:
  ::Xsmp::EntryPoint IncrementCount;
  virtual void _IncrementCount() = 0;
  ::Xsmp::EventSink<::Smp::Int32> Add;
  virtual void _Add(::Smp::IObject *sender, ::Smp::Int32) = 0;

protected:
  ::Smp::Int32 count;
};
} // namespace Example

#endif // EXAMPLE_COUNTERGEN_H_
