# Copyright 2023-2024 THALES ALENIA SPACE FRANCE. All rights reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -----------------------------------------------------------------------------
# File Name 	: xsmp_tests/Xsmp/Tests/__init__.py
# Generated by 	: PythonGenerator-1.1.0
# -----------------------------------------------------------------------------
# This file is auto-generated. Do not edit otherwise your changes will be lost.

from . import Types
import ecss_smp

class ModelWithSimpleFields:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("df6ddf61-c676-47f5-8764-fc6d889318ff")
class ModelWithArrayFields:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("120f3848-02d8-4cec-a0c2-32e3e5714e1a")
class ModelWithSimpleArrayFields:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("ea180c7c-4a55-4b42-8029-569a0b622c00")
class ModelWithEvents:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("bc8e7b0e-b820-4404-a397-9e8df27bb93c")
class ModelWithOperations:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("5c52ca42-4992-4401-9408-8d994b1fbabe")
class ModelWithProperties:
    uuid: ecss_smp.Smp.Uuid = ecss_smp.Smp.Uuid("3264ed26-0085-4238-8ecf-d099715341e2")

del ecss_smp
