// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : XsmpLinkRegistryGen.h
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Services/XsmpLinkRegistryGen.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_SERVICES_XSMPLINKREGISTRYGEN_H_
#define XSMP_SERVICES_XSMPLINKREGISTRYGEN_H_

// ----------------------------------------------------------------------------
// --------------------------- Forward Declarations ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Services {
class XsmpLinkRegistry;
} // namespace Xsmp::Services

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/IComposite.h>
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <Smp/Services/ILinkRegistry.h>
#include <Xsmp/Service.h>

// ----------------------------------------------------------------------------
// --------------------------- Types and Interfaces ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Services {
/// Universally unique identifier of type XsmpLinkRegistry.
inline constexpr ::Smp::Uuid Uuid_XsmpLinkRegistry{
    0xcb874041U, 0x3bf6U, 0x42c0U, 0x8a7aU, 0xac8fd2809367U};

class XsmpLinkRegistryGen : public ::Xsmp::Service,
                            public virtual ::Smp::Services::ILinkRegistry {
  friend class ::Xsmp::Services::XsmpLinkRegistry;

public:
  /// Constructor setting name, description, parent and simulator.
  /// @param name Name of new Service instance.
  /// @param description Description of new Service instance.
  /// @param parent Parent of new Service instance.
  /// @param simulator The simulator instance.
  XsmpLinkRegistryGen(::Smp::String8 name, ::Smp::String8 description,
                      ::Smp::IComposite *parent, ::Smp::ISimulator *simulator);
  /// deleted copy constructor
  XsmpLinkRegistryGen(const XsmpLinkRegistryGen &) = delete;
  /// deleted move constructor
  XsmpLinkRegistryGen(XsmpLinkRegistryGen &&) = delete;
  /// deleted copy assignment
  XsmpLinkRegistryGen &operator=(const XsmpLinkRegistryGen &) = delete;
  /// deleted move assignment
  XsmpLinkRegistryGen &operator=(XsmpLinkRegistryGen &&) = delete;

  /// Virtual destructor to release memory.
  ~XsmpLinkRegistryGen() override = default;

  /// Request the Service to publish its fields, properties and
  /// operations against the provided publication receiver.
  /// @param   receiver Publication receiver.
  /// @throws  Smp::InvalidComponentState
  void Publish(::Smp::IPublication *receiver) override;

  /// Request the Service to perform any custom configuration. The
  /// component can create and configure other components using the field
  /// values of its published fields.
  /// @param   logger Logger service for logging of error messages during
  ///          configuration.
  /// @param   linkRegistry Reference to the link registry services, so
  ///          that the Service can register links that it creates
  ///          during configuration.
  /// @throws  Smp::InvalidComponentState
  void Configure(::Smp::Services::ILogger *logger,
                 ::Smp::Services::ILinkRegistry *linkRegistry) override;

  /// Allow the Service to connect to the simulator and its simulation
  /// services.
  /// @param   simulator Simulation Environment that hosts the Service.
  /// @throws  Smp::InvalidComponentState
  void Connect(::Smp::ISimulator *simulator) override;

  /// Ask the Service to disconnect from the simulator and all its
  /// simulation services.
  /// @throws  Smp::InvalidComponentState
  void Disconnect() override;

  /// Get Universally Unique Identifier of the Service.
  /// @return  Universally Unique Identifier of the Service.
  const ::Smp::Uuid &GetUuid() const override;
};
} // namespace Xsmp::Services

#endif // XSMP_SERVICES_XSMPLINKREGISTRYGEN_H_
