// Copyright 2023 THALES ALENIA SPACE FRANCE. All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// -----------------------------------------------------------------------------
// File Name    : XsmpTimeKeeperGen.h
// Generated by : XsmpSdkGenerator-${qualifiedVersion}
// -----------------------------------------------------------------------------
/// @file Xsmp/Services/XsmpTimeKeeperGen.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_SERVICES_XSMPTIMEKEEPERGEN_H_
#define XSMP_SERVICES_XSMPTIMEKEEPERGEN_H_

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "Smp/IEntryPoint.h"
#include "Smp/IPersist.h"
#include "Smp/ISimulator.h"
#include "Smp/Publication/ITypeRegistry.h"
#include "Smp/Services/ITimeKeeper.h"
#include "Xsmp/EntryPointPublisher.h"
#include "Xsmp/Service.h"
#include <type_traits>

// ----------------------------------------------------------------------------
// ------------------------ Types and Interfaces ------------------------
// ----------------------------------------------------------------------------

namespace Xsmp {
namespace Services {
// forward declaration of user class
class XsmpTimeKeeper;
/// Universally unique identifier of type XsmpTimeKeeper.
static constexpr ::Smp::Uuid Uuid_XsmpTimeKeeper { 0x00e6747eU, 0x2047U,
        0x4c13U, 0xbda5U, 0xbaf50819e768U };

class XsmpTimeKeeperGen: public ::Xsmp::Service,
        public virtual ::Smp::Services::ITimeKeeper,
        public virtual ::Smp::IPersist,
        public virtual ::Xsmp::EntryPointPublisher {

    friend class ::Xsmp::Services::XsmpTimeKeeper;

public:
    // ------------------------------------------------------------------------------------
    // -------------------------- Constructors/Destructor --------------------------
    // ------------------------------------------------------------------------------------

    /// Constructor setting name, description, parent and simulator.
    /// @param name Name of new model instance.
    /// @param description Description of new model instance.
    /// @param parent Parent of new model instance.
    /// @param simulator The simulator instance.
    XsmpTimeKeeperGen(::Smp::String8 name, ::Smp::String8 description,
            ::Smp::IObject *parent, ::Smp::ISimulator *simulator);
    /// deleted copy constructor
    XsmpTimeKeeperGen(const XsmpTimeKeeperGen&) = delete;
    /// deleted move constructor
    XsmpTimeKeeperGen(XsmpTimeKeeperGen&&) = delete;
    /// deleted copy assignment
    XsmpTimeKeeperGen& operator=(const XsmpTimeKeeperGen&) = delete;
    /// deleted move assignment
    XsmpTimeKeeperGen& operator=(XsmpTimeKeeperGen&&) = delete;

    /// Virtual destructor to release memory.
    ~XsmpTimeKeeperGen() override;

    // ----------------------------------------------------------------------------------
    // -------------------------------- IComponent ---------------------------------
    // ----------------------------------------------------------------------------------

    /// Publish fields, operations and properties of the model.
    /// @param receiver Publication receiver.
    void Publish(::Smp::IPublication *receiver) override;

    /// Request for configuration.
    /// @param logger Logger to use for log messages during Configure().
    /// @param linkRegistry Link Registry to use for registration of
    ///         links created during Configure() or later.
    void Configure(::Smp::Services::ILogger *logger,
            ::Smp::Services::ILinkRegistry *linkRegistry) override;

    /// Connect model to simulator.
    /// @param simulator Simulation Environment that hosts the model.
    ///
    void Connect(::Smp::ISimulator *simulator) override;

    /// Disconnect model to simulator.
    /// @throws Smp::InvalidComponentState
    void Disconnect() override;

    /// Return the Universally Unique Identifier of the Model.
    /// @return Universally Unique Identifier of the Model.
    const Smp::Uuid& GetUuid() const override;

    ::Smp::IEntryPoint *PreSimTimeChange;
    virtual void _PreSimTimeChange() = 0;
    ::Smp::IEntryPoint *PostSimTimeChange;
    virtual void _PostSimTimeChange() = 0;
};
} // namespace Services
} // namespace Xsmp

#endif // XSMP_SERVICES_XSMPTIMEKEEPERGEN_H_
