// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : XsmpEventManagerGen.h
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Services/XsmpEventManagerGen.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_SERVICES_XSMPEVENTMANAGERGEN_H_
#define XSMP_SERVICES_XSMPEVENTMANAGERGEN_H_

// ----------------------------------------------------------------------------
// --------------------------- Forward Declarations ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Services {
class XsmpEventManager;
} // namespace Xsmp::Services

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/IComposite.h>
#include <Smp/IPersist.h>
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <Smp/Services/IEventManager.h>
#include <Xsmp/Service.h>

// ----------------------------------------------------------------------------
// --------------------------- Types and Interfaces ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Services {
/// Universally unique identifier of type XsmpEventManager.
inline constexpr ::Smp::Uuid Uuid_XsmpEventManager{
    0x840d13a6U, 0x7b41U, 0x4f3dU, 0xa25cU, 0xdab597135a51U};

class XsmpEventManagerGen : public ::Xsmp::Service,
                            public virtual ::Smp::Services::IEventManager,
                            public virtual ::Smp::IPersist {
  friend class ::Xsmp::Services::XsmpEventManager;

public:
  /// Constructor setting name, description, parent and simulator.
  /// @param name Name of new Service instance.
  /// @param description Description of new Service instance.
  /// @param parent Parent of new Service instance.
  /// @param simulator The simulator instance.
  XsmpEventManagerGen(::Smp::String8 name, ::Smp::String8 description,
                      ::Smp::IComposite *parent, ::Smp::ISimulator *simulator);
  /// deleted copy constructor
  XsmpEventManagerGen(const XsmpEventManagerGen &) = delete;
  /// deleted move constructor
  XsmpEventManagerGen(XsmpEventManagerGen &&) = delete;
  /// deleted copy assignment
  XsmpEventManagerGen &operator=(const XsmpEventManagerGen &) = delete;
  /// deleted move assignment
  XsmpEventManagerGen &operator=(XsmpEventManagerGen &&) = delete;

  /// Virtual destructor to release memory.
  ~XsmpEventManagerGen() override = default;

  /// Request the Service to publish its fields, properties and
  /// operations against the provided publication receiver.
  /// @param   receiver Publication receiver.
  /// @throws  Smp::InvalidComponentState
  void Publish(::Smp::IPublication *receiver) override;

  /// Request the Service to perform any custom configuration. The
  /// component can create and configure other components using the field
  /// values of its published fields.
  /// @param   logger Logger service for logging of error messages during
  ///          configuration.
  /// @param   linkRegistry Reference to the link registry services, so
  ///          that the Service can register links that it creates
  ///          during configuration.
  /// @throws  Smp::InvalidComponentState
  void Configure(::Smp::Services::ILogger *logger,
                 ::Smp::Services::ILinkRegistry *linkRegistry) override;

  /// Allow the Service to connect to the simulator and its simulation
  /// services.
  /// @param   simulator Simulation Environment that hosts the Service.
  /// @throws  Smp::InvalidComponentState
  void Connect(::Smp::ISimulator *simulator) override;

  /// Ask the Service to disconnect from the simulator and all its
  /// simulation services.
  /// @throws  Smp::InvalidComponentState
  void Disconnect() override;

  /// Get Universally Unique Identifier of the Service.
  /// @return  Universally Unique Identifier of the Service.
  const ::Smp::Uuid &GetUuid() const override;
};
} // namespace Xsmp::Services

#endif // XSMP_SERVICES_XSMPEVENTMANAGERGEN_H_
