// Copyright 2023 THALES ALENIA SPACE FRANCE. All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// -----------------------------------------------------------------------------
// File Name    : Int64Array.h
// Generated by : XsmpSdkGenerator-${qualifiedVersion}
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/Types/Int64Array.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_TESTS_TYPES_INT64ARRAY_H_
#define XSMP_TESTS_TYPES_INT64ARRAY_H_

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "Smp/PrimitiveTypes.h"
#include "Smp/Publication/ITypeRegistry.h"
#include "Xsmp/Array.h"

// ----------------------------------------------------------------------------
// ------------------------ Types and Interfaces ------------------------
// ----------------------------------------------------------------------------

namespace Xsmp {
namespace Tests {
namespace Types {
using Int64Array = ::Xsmp::Array<::Smp::Int64, 3>;

/// Universally unique identifier of type Int64Array.
static constexpr ::Smp::Uuid Uuid_Int64Array { 0xdcf5089aU, 0x377bU, 0x4853U,
        0x8049U, 0x74662d385dffU };

void _Register_Int64Array(::Smp::Publication::ITypeRegistry *registry);
} // namespace Types
} // namespace Tests
} // namespace Xsmp

#endif // XSMP_TESTS_TYPES_INT64ARRAY_H_
