// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : SimpleStructure.cpp
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/Types/SimpleStructure.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/Publication/IStructureType.h>
#include <Smp/ViewKind.h>
#include <Xsmp/Tests/Types/SimpleStructure.h>
#include <cstddef>

namespace Xsmp::Tests::Types {

void SimpleStructure::_Register(::Smp::Publication::ITypeRegistry *registry) {
  auto *type = registry->AddStructureType(
      "SimpleStructure",                         // Name
      "",                                        // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure // UUID
  );

  // Register the Fields of the Class
  type->AddField("boolean",                          // Name
                 "",                                 // Description
                 ::Smp::Uuids::Uuid_Bool,            // Type UUID
                 offsetof(SimpleStructure, boolean), // Field offset
                 ::Smp::ViewKind::VK_All,            // View Kind
                 true,                               // State
                 false,                              // Input
                 false                               // Output
  );
  type->AddField("char8",                          // Name
                 "",                               // Description
                 ::Smp::Uuids::Uuid_Char8,         // Type UUID
                 offsetof(SimpleStructure, char8), // Field offset
                 ::Smp::ViewKind::VK_All,          // View Kind
                 true,                             // State
                 false,                            // Input
                 false                             // Output
  );
  type->AddField("enum1",                          // Name
                 "",                               // Description
                 ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
                 offsetof(SimpleStructure, enum1), // Field offset
                 ::Smp::ViewKind::VK_All,          // View Kind
                 true,                             // State
                 false,                            // Input
                 false                             // Output
  );
  type->AddField("string1",                          // Name
                 "",                                 // Description
                 ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
                 offsetof(SimpleStructure, string1), // Field offset
                 ::Smp::ViewKind::VK_All,            // View Kind
                 true,                               // State
                 false,                              // Input
                 false                               // Output
  );
  type->AddField("float1",                          // Name
                 "",                                // Description
                 ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
                 offsetof(SimpleStructure, float1), // Field offset
                 ::Smp::ViewKind::VK_All,           // View Kind
                 true,                              // State
                 false,                             // Input
                 false                              // Output
  );
  type->AddField("integer1",                          // Name
                 "",                                  // Description
                 ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
                 offsetof(SimpleStructure, integer1), // Field offset
                 ::Smp::ViewKind::VK_All,             // View Kind
                 true,                                // State
                 false,                               // Input
                 false                                // Output
  );
}

} // namespace Xsmp::Tests::Types