// Copyright 2023 THALES ALENIA SPACE FRANCE. All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// -----------------------------------------------------------------------------
// File Name    : String1Array.h
// Generated by : XsmpSdkGenerator-${qualifiedVersion}
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/Types/String1Array.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_TESTS_TYPES_STRING1ARRAY_H_
#define XSMP_TESTS_TYPES_STRING1ARRAY_H_

// ----------------------------------------------------------------------------
// ---------------------------- Include Header Files --------------------
// ----------------------------------------------------------------------------

#include "Smp/PrimitiveTypes.h"
#include "Smp/Publication/ITypeRegistry.h"
#include "Xsmp/Array.h"
#include "Xsmp/Tests/Types/String1.h"

// ----------------------------------------------------------------------------
// ------------------------ Types and Interfaces ------------------------
// ----------------------------------------------------------------------------

namespace Xsmp {
namespace Tests {
namespace Types {
using String1Array = ::Xsmp::Array<::Xsmp::Tests::Types::String1, 3>;

/// Universally unique identifier of type String1Array.
static constexpr ::Smp::Uuid Uuid_String1Array { 0x44c17ffdU, 0x7bebU, 0x4d62U,
        0xbcb9U, 0x0d303242bfc6U };

void _Register_String1Array(::Smp::Publication::ITypeRegistry *registry);
} // namespace Types
} // namespace Tests
} // namespace Xsmp

#endif // XSMP_TESTS_TYPES_STRING1ARRAY_H_
