// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : StructureWithCustomFields.cpp
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/Types/StructureWithCustomFields.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/Publication/IStructureType.h>
#include <Smp/ViewKind.h>
#include <Xsmp/Tests/Types/StructureWithCustomFields.h>
#include <cstddef>

namespace Xsmp::Tests::Types {

void StructureWithCustomFields::_Register(
    ::Smp::Publication::ITypeRegistry *registry) {
  auto *type = registry->AddStructureType(
      "StructureWithCustomFields",                         // Name
      "",                                                  // Description
      ::Xsmp::Tests::Types::Uuid_StructureWithCustomFields // UUID
  );

  // Register the Fields of the Class
  type->AddField(
      "booleanInput",                                    // Name
      "",                                                // Description
      ::Smp::Uuids::Uuid_Bool,                           // Type UUID
      offsetof(StructureWithCustomFields, booleanInput), // Field offset
      ::Smp::ViewKind::VK_All,                           // View Kind
      true,                                              // State
      true,                                              // Input
      false                                              // Output
  );
  type->AddField(
      "char8Input",                                    // Name
      "",                                              // Description
      ::Smp::Uuids::Uuid_Char8,                        // Type UUID
      offsetof(StructureWithCustomFields, char8Input), // Field offset
      ::Smp::ViewKind::VK_All,                         // View Kind
      true,                                            // State
      true,                                            // Input
      false                                            // Output
  );
  type->AddField(
      "enum1Input",                                    // Name
      "",                                              // Description
      ::Xsmp::Tests::Types::Uuid_Enum1,                // Type UUID
      offsetof(StructureWithCustomFields, enum1Input), // Field offset
      ::Smp::ViewKind::VK_All,                         // View Kind
      true,                                            // State
      true,                                            // Input
      false                                            // Output
  );
  type->AddField(
      "string1Input",                                    // Name
      "",                                                // Description
      ::Xsmp::Tests::Types::Uuid_String1,                // Type UUID
      offsetof(StructureWithCustomFields, string1Input), // Field offset
      ::Smp::ViewKind::VK_All,                           // View Kind
      true,                                              // State
      true,                                              // Input
      false                                              // Output
  );
  type->AddField(
      "float1Input",                                    // Name
      "",                                               // Description
      ::Xsmp::Tests::Types::Uuid_Float1,                // Type UUID
      offsetof(StructureWithCustomFields, float1Input), // Field offset
      ::Smp::ViewKind::VK_All,                          // View Kind
      true,                                             // State
      true,                                             // Input
      false                                             // Output
  );
  type->AddField(
      "integer1Input",                                    // Name
      "",                                                 // Description
      ::Xsmp::Tests::Types::Uuid_Integer1,                // Type UUID
      offsetof(StructureWithCustomFields, integer1Input), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      true,                                               // Input
      false                                               // Output
  );
  type->AddField(
      "struct1Input",                                    // Name
      "",                                                // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure,        // Type UUID
      offsetof(StructureWithCustomFields, struct1Input), // Field offset
      ::Smp::ViewKind::VK_All,                           // View Kind
      true,                                              // State
      true,                                              // Input
      false                                              // Output
  );
  type->AddField(
      "booleanTransient",                                    // Name
      "",                                                    // Description
      ::Smp::Uuids::Uuid_Bool,                               // Type UUID
      offsetof(StructureWithCustomFields, booleanTransient), // Field offset
      ::Smp::ViewKind::VK_All,                               // View Kind
      false,                                                 // State
      false,                                                 // Input
      false                                                  // Output
  );
  type->AddField(
      "char8Transient",                                    // Name
      "",                                                  // Description
      ::Smp::Uuids::Uuid_Char8,                            // Type UUID
      offsetof(StructureWithCustomFields, char8Transient), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      false,                                               // State
      false,                                               // Input
      false                                                // Output
  );
  type->AddField(
      "enum1Transient",                                    // Name
      "",                                                  // Description
      ::Xsmp::Tests::Types::Uuid_Enum1,                    // Type UUID
      offsetof(StructureWithCustomFields, enum1Transient), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      false,                                               // State
      false,                                               // Input
      false                                                // Output
  );
  type->AddField(
      "string1Transient",                                    // Name
      "",                                                    // Description
      ::Xsmp::Tests::Types::Uuid_String1,                    // Type UUID
      offsetof(StructureWithCustomFields, string1Transient), // Field offset
      ::Smp::ViewKind::VK_All,                               // View Kind
      false,                                                 // State
      false,                                                 // Input
      false                                                  // Output
  );
  type->AddField(
      "float1Transient",                                    // Name
      "",                                                   // Description
      ::Xsmp::Tests::Types::Uuid_Float1,                    // Type UUID
      offsetof(StructureWithCustomFields, float1Transient), // Field offset
      ::Smp::ViewKind::VK_All,                              // View Kind
      false,                                                // State
      false,                                                // Input
      false                                                 // Output
  );
  type->AddField(
      "integer1Transient",                                    // Name
      "",                                                     // Description
      ::Xsmp::Tests::Types::Uuid_Integer1,                    // Type UUID
      offsetof(StructureWithCustomFields, integer1Transient), // Field offset
      ::Smp::ViewKind::VK_All,                                // View Kind
      false,                                                  // State
      false,                                                  // Input
      false                                                   // Output
  );
  type->AddField(
      "struct1Transient",                                    // Name
      "",                                                    // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure,            // Type UUID
      offsetof(StructureWithCustomFields, struct1Transient), // Field offset
      ::Smp::ViewKind::VK_All,                               // View Kind
      false,                                                 // State
      false,                                                 // Input
      false                                                  // Output
  );
  type->AddField(
      "booleanOutput",                                    // Name
      "",                                                 // Description
      ::Smp::Uuids::Uuid_Bool,                            // Type UUID
      offsetof(StructureWithCustomFields, booleanOutput), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      false,                                              // Input
      true                                                // Output
  );
  type->AddField(
      "char8Output",                                    // Name
      "",                                               // Description
      ::Smp::Uuids::Uuid_Char8,                         // Type UUID
      offsetof(StructureWithCustomFields, char8Output), // Field offset
      ::Smp::ViewKind::VK_All,                          // View Kind
      true,                                             // State
      false,                                            // Input
      true                                              // Output
  );
  type->AddField(
      "enum1Output",                                    // Name
      "",                                               // Description
      ::Xsmp::Tests::Types::Uuid_Enum1,                 // Type UUID
      offsetof(StructureWithCustomFields, enum1Output), // Field offset
      ::Smp::ViewKind::VK_All,                          // View Kind
      true,                                             // State
      false,                                            // Input
      true                                              // Output
  );
  type->AddField(
      "string1Output",                                    // Name
      "",                                                 // Description
      ::Xsmp::Tests::Types::Uuid_String1,                 // Type UUID
      offsetof(StructureWithCustomFields, string1Output), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      false,                                              // Input
      true                                                // Output
  );
  type->AddField(
      "float1Output",                                    // Name
      "",                                                // Description
      ::Xsmp::Tests::Types::Uuid_Float1,                 // Type UUID
      offsetof(StructureWithCustomFields, float1Output), // Field offset
      ::Smp::ViewKind::VK_All,                           // View Kind
      true,                                              // State
      false,                                             // Input
      true                                               // Output
  );
  type->AddField(
      "integer1Output",                                    // Name
      "",                                                  // Description
      ::Xsmp::Tests::Types::Uuid_Integer1,                 // Type UUID
      offsetof(StructureWithCustomFields, integer1Output), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      true,                                                // State
      false,                                               // Input
      true                                                 // Output
  );
  type->AddField(
      "struct1Output",                                    // Name
      "",                                                 // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure,         // Type UUID
      offsetof(StructureWithCustomFields, struct1Output), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      false,                                              // Input
      true                                                // Output
  );
  type->AddField(
      "booleanForcible",                                    // Name
      "",                                                   // Description
      ::Smp::Uuids::Uuid_Bool,                              // Type UUID
      offsetof(StructureWithCustomFields, booleanForcible), // Field offset
      ::Smp::ViewKind::VK_All,                              // View Kind
      true,                                                 // State
      false,                                                // Input
      false                                                 // Output
  );
  type->AddField(
      "char8Forcible",                                    // Name
      "",                                                 // Description
      ::Smp::Uuids::Uuid_Char8,                           // Type UUID
      offsetof(StructureWithCustomFields, char8Forcible), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      false,                                              // Input
      false                                               // Output
  );
  type->AddField(
      "enum1Forcible",                                    // Name
      "",                                                 // Description
      ::Xsmp::Tests::Types::Uuid_Enum1,                   // Type UUID
      offsetof(StructureWithCustomFields, enum1Forcible), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      false,                                              // Input
      false                                               // Output
  );
  type->AddField(
      "string1Forcible",                                    // Name
      "",                                                   // Description
      ::Xsmp::Tests::Types::Uuid_String1,                   // Type UUID
      offsetof(StructureWithCustomFields, string1Forcible), // Field offset
      ::Smp::ViewKind::VK_All,                              // View Kind
      true,                                                 // State
      false,                                                // Input
      false                                                 // Output
  );
  type->AddField(
      "float1Forcible",                                    // Name
      "",                                                  // Description
      ::Xsmp::Tests::Types::Uuid_Float1,                   // Type UUID
      offsetof(StructureWithCustomFields, float1Forcible), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      true,                                                // State
      false,                                               // Input
      false                                                // Output
  );
  type->AddField(
      "integer1Forcible",                                    // Name
      "",                                                    // Description
      ::Xsmp::Tests::Types::Uuid_Integer1,                   // Type UUID
      offsetof(StructureWithCustomFields, integer1Forcible), // Field offset
      ::Smp::ViewKind::VK_All,                               // View Kind
      true,                                                  // State
      false,                                                 // Input
      false                                                  // Output
  );
  type->AddField(
      "struct1Forcible",                                    // Name
      "",                                                   // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure,           // Type UUID
      offsetof(StructureWithCustomFields, struct1Forcible), // Field offset
      ::Smp::ViewKind::VK_All,                              // View Kind
      true,                                                 // State
      false,                                                // Input
      false                                                 // Output
  );
  type->AddField(
      "booleanFailure",                                    // Name
      "",                                                  // Description
      ::Smp::Uuids::Uuid_Bool,                             // Type UUID
      offsetof(StructureWithCustomFields, booleanFailure), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      true,                                                // State
      false,                                               // Input
      false                                                // Output
  );
  type->AddField(
      "char8Failure",                                    // Name
      "",                                                // Description
      ::Smp::Uuids::Uuid_Char8,                          // Type UUID
      offsetof(StructureWithCustomFields, char8Failure), // Field offset
      ::Smp::ViewKind::VK_All,                           // View Kind
      true,                                              // State
      false,                                             // Input
      false                                              // Output
  );
  type->AddField(
      "enum1Failure",                                    // Name
      "",                                                // Description
      ::Xsmp::Tests::Types::Uuid_Enum1,                  // Type UUID
      offsetof(StructureWithCustomFields, enum1Failure), // Field offset
      ::Smp::ViewKind::VK_All,                           // View Kind
      true,                                              // State
      false,                                             // Input
      false                                              // Output
  );
  type->AddField(
      "string1Failure",                                    // Name
      "",                                                  // Description
      ::Xsmp::Tests::Types::Uuid_String1,                  // Type UUID
      offsetof(StructureWithCustomFields, string1Failure), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      true,                                                // State
      false,                                               // Input
      false                                                // Output
  );
  type->AddField(
      "float1Failure",                                    // Name
      "",                                                 // Description
      ::Xsmp::Tests::Types::Uuid_Float1,                  // Type UUID
      offsetof(StructureWithCustomFields, float1Failure), // Field offset
      ::Smp::ViewKind::VK_All,                            // View Kind
      true,                                               // State
      false,                                              // Input
      false                                               // Output
  );
  type->AddField(
      "integer1Failure",                                    // Name
      "",                                                   // Description
      ::Xsmp::Tests::Types::Uuid_Integer1,                  // Type UUID
      offsetof(StructureWithCustomFields, integer1Failure), // Field offset
      ::Smp::ViewKind::VK_All,                              // View Kind
      true,                                                 // State
      false,                                                // Input
      false                                                 // Output
  );
  type->AddField(
      "struct1Failure",                                    // Name
      "",                                                  // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure,          // Type UUID
      offsetof(StructureWithCustomFields, struct1Failure), // Field offset
      ::Smp::ViewKind::VK_All,                             // View Kind
      true,                                                // State
      false,                                               // Input
      false                                                // Output
  );
  type->AddField(
      "booleanAll",                                    // Name
      "",                                              // Description
      ::Smp::Uuids::Uuid_Bool,                         // Type UUID
      offsetof(StructureWithCustomFields, booleanAll), // Field offset
      ::Smp::ViewKind::VK_All,                         // View Kind
      false,                                           // State
      true,                                            // Input
      true                                             // Output
  );
  type->AddField("char8All",                                    // Name
                 "",                                            // Description
                 ::Smp::Uuids::Uuid_Char8,                      // Type UUID
                 offsetof(StructureWithCustomFields, char8All), // Field offset
                 ::Smp::ViewKind::VK_All,                       // View Kind
                 false,                                         // State
                 true,                                          // Input
                 true                                           // Output
  );
  type->AddField("enum1All",                                    // Name
                 "",                                            // Description
                 ::Xsmp::Tests::Types::Uuid_Enum1,              // Type UUID
                 offsetof(StructureWithCustomFields, enum1All), // Field offset
                 ::Smp::ViewKind::VK_All,                       // View Kind
                 false,                                         // State
                 true,                                          // Input
                 true                                           // Output
  );
  type->AddField(
      "string1All",                                    // Name
      "",                                              // Description
      ::Xsmp::Tests::Types::Uuid_String1,              // Type UUID
      offsetof(StructureWithCustomFields, string1All), // Field offset
      ::Smp::ViewKind::VK_All,                         // View Kind
      false,                                           // State
      true,                                            // Input
      true                                             // Output
  );
  type->AddField("float1All",                                    // Name
                 "",                                             // Description
                 ::Xsmp::Tests::Types::Uuid_Float1,              // Type UUID
                 offsetof(StructureWithCustomFields, float1All), // Field offset
                 ::Smp::ViewKind::VK_All,                        // View Kind
                 false,                                          // State
                 true,                                           // Input
                 true                                            // Output
  );
  type->AddField(
      "integer1All",                                    // Name
      "",                                               // Description
      ::Xsmp::Tests::Types::Uuid_Integer1,              // Type UUID
      offsetof(StructureWithCustomFields, integer1All), // Field offset
      ::Smp::ViewKind::VK_All,                          // View Kind
      false,                                            // State
      true,                                             // Input
      true                                              // Output
  );
  type->AddField(
      "struct1All",                                    // Name
      "",                                              // Description
      ::Xsmp::Tests::Types::Uuid_SimpleStructure,      // Type UUID
      offsetof(StructureWithCustomFields, struct1All), // Field offset
      ::Smp::ViewKind::VK_All,                         // View Kind
      false,                                           // State
      true,                                            // Input
      true                                             // Output
  );
}

} // namespace Xsmp::Tests::Types