// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : StructureWithCustomFields.h
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/Types/StructureWithCustomFields.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_TESTS_TYPES_STRUCTUREWITHCUSTOMFIELDS_H_
#define XSMP_TESTS_TYPES_STRUCTUREWITHCUSTOMFIELDS_H_

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <Smp/ViewKind.h>
#include <Xsmp/Tests/Types/Enum1.h>
#include <Xsmp/Tests/Types/Float1.h>
#include <Xsmp/Tests/Types/Integer1.h>
#include <Xsmp/Tests/Types/SimpleStructure.h>
#include <Xsmp/Tests/Types/String1.h>

// ----------------------------------------------------------------------------
// --------------------------- Types and Interfaces ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Tests::Types {
struct StructureWithCustomFields {
  ::Smp::Bool booleanInput;
  ::Smp::Char8 char8Input;
  ::Xsmp::Tests::Types::Enum1 enum1Input;
  ::Xsmp::Tests::Types::String1 string1Input;
  ::Xsmp::Tests::Types::Float1 float1Input;
  ::Xsmp::Tests::Types::Integer1 integer1Input;
  ::Xsmp::Tests::Types::SimpleStructure struct1Input;
  ::Smp::Bool booleanTransient;
  ::Smp::Char8 char8Transient;
  ::Xsmp::Tests::Types::Enum1 enum1Transient;
  ::Xsmp::Tests::Types::String1 string1Transient;
  ::Xsmp::Tests::Types::Float1 float1Transient;
  ::Xsmp::Tests::Types::Integer1 integer1Transient;
  ::Xsmp::Tests::Types::SimpleStructure struct1Transient;
  ::Smp::Bool booleanOutput;
  ::Smp::Char8 char8Output;
  ::Xsmp::Tests::Types::Enum1 enum1Output;
  ::Xsmp::Tests::Types::String1 string1Output;
  ::Xsmp::Tests::Types::Float1 float1Output;
  ::Xsmp::Tests::Types::Integer1 integer1Output;
  ::Xsmp::Tests::Types::SimpleStructure struct1Output;
  ::Smp::Bool booleanForcible;
  ::Smp::Char8 char8Forcible;
  ::Xsmp::Tests::Types::Enum1 enum1Forcible;
  ::Xsmp::Tests::Types::String1 string1Forcible;
  ::Xsmp::Tests::Types::Float1 float1Forcible;
  ::Xsmp::Tests::Types::Integer1 integer1Forcible;
  ::Xsmp::Tests::Types::SimpleStructure struct1Forcible;
  ::Smp::Bool booleanFailure;
  ::Smp::Char8 char8Failure;
  ::Xsmp::Tests::Types::Enum1 enum1Failure;
  ::Xsmp::Tests::Types::String1 string1Failure;
  ::Xsmp::Tests::Types::Float1 float1Failure;
  ::Xsmp::Tests::Types::Integer1 integer1Failure;
  ::Xsmp::Tests::Types::SimpleStructure struct1Failure;
  ::Smp::Bool booleanAll;
  ::Smp::Char8 char8All;
  ::Xsmp::Tests::Types::Enum1 enum1All;
  ::Xsmp::Tests::Types::String1 string1All;
  ::Xsmp::Tests::Types::Float1 float1All;
  ::Xsmp::Tests::Types::Integer1 integer1All;
  ::Xsmp::Tests::Types::SimpleStructure struct1All;

  static void _Register(::Smp::Publication::ITypeRegistry *registry);

  template <typename _BASE> struct _Field : public _BASE {
    _Field(::Smp::Publication::ITypeRegistry *typeRegistry,
           ::Smp::Uuid typeUuid, ::Smp::String8 name,
           ::Smp::String8 description = "", ::Smp::IObject *parent = nullptr,
           ::Smp::ViewKind view = ::Smp::ViewKind::VK_All)
        : _Field(typeRegistry, typeUuid, name, description, parent, view,
                 ::Xsmp::Tests::Types::StructureWithCustomFields{}) {}
    _Field(::Smp::Publication::ITypeRegistry *typeRegistry,
           ::Smp::Uuid typeUuid, ::Smp::String8 name,
           ::Smp::String8 description, ::Smp::IObject *parent,
           ::Smp::ViewKind view,
           const ::Xsmp::Tests::Types::StructureWithCustomFields &value)
        : _BASE(typeRegistry, typeUuid, name, description, parent, view),
          // Field booleanInput
          booleanInput{
              typeRegistry,            // Type Registry
              ::Smp::Uuids::Uuid_Bool, // Type UUID
              "booleanInput",          // Name
              "",                      // Description
              this,                    // Parent
              view,                    // View Kind
              value.booleanInput       // Value
          },
          // Field char8Input
          char8Input{
              typeRegistry,             // Type Registry
              ::Smp::Uuids::Uuid_Char8, // Type UUID
              "char8Input",             // Name
              "",                       // Description
              this,                     // Parent
              view,                     // View Kind
              value.char8Input          // Value
          },
          // Field enum1Input
          enum1Input{
              typeRegistry,                     // Type Registry
              ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
              "enum1Input",                     // Name
              "",                               // Description
              this,                             // Parent
              view,                             // View Kind
              value.enum1Input                  // Value
          },
          // Field string1Input
          string1Input{
              typeRegistry,                       // Type Registry
              ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
              "string1Input",                     // Name
              "",                                 // Description
              this,                               // Parent
              view,                               // View Kind
              value.string1Input                  // Value
          },
          // Field float1Input
          float1Input{
              typeRegistry,                      // Type Registry
              ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
              "float1Input",                     // Name
              "",                                // Description
              this,                              // Parent
              view,                              // View Kind
              value.float1Input                  // Value
          },
          // Field integer1Input
          integer1Input{
              typeRegistry,                        // Type Registry
              ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
              "integer1Input",                     // Name
              "",                                  // Description
              this,                                // Parent
              view,                                // View Kind
              value.integer1Input                  // Value
          },
          // Field struct1Input
          struct1Input{
              typeRegistry,                               // Type Registry
              ::Xsmp::Tests::Types::Uuid_SimpleStructure, // Type UUID
              "struct1Input",                             // Name
              "",                                         // Description
              this,                                       // Parent
              view,                                       // View Kind
              value.struct1Input                          // Value
          },
          // Field booleanTransient
          booleanTransient{
              typeRegistry,            // Type Registry
              ::Smp::Uuids::Uuid_Bool, // Type UUID
              "booleanTransient",      // Name
              "",                      // Description
              this,                    // Parent
              view,                    // View Kind
              value.booleanTransient   // Value
          },
          // Field char8Transient
          char8Transient{
              typeRegistry,             // Type Registry
              ::Smp::Uuids::Uuid_Char8, // Type UUID
              "char8Transient",         // Name
              "",                       // Description
              this,                     // Parent
              view,                     // View Kind
              value.char8Transient      // Value
          },
          // Field enum1Transient
          enum1Transient{
              typeRegistry,                     // Type Registry
              ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
              "enum1Transient",                 // Name
              "",                               // Description
              this,                             // Parent
              view,                             // View Kind
              value.enum1Transient              // Value
          },
          // Field string1Transient
          string1Transient{
              typeRegistry,                       // Type Registry
              ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
              "string1Transient",                 // Name
              "",                                 // Description
              this,                               // Parent
              view,                               // View Kind
              value.string1Transient              // Value
          },
          // Field float1Transient
          float1Transient{
              typeRegistry,                      // Type Registry
              ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
              "float1Transient",                 // Name
              "",                                // Description
              this,                              // Parent
              view,                              // View Kind
              value.float1Transient              // Value
          },
          // Field integer1Transient
          integer1Transient{
              typeRegistry,                        // Type Registry
              ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
              "integer1Transient",                 // Name
              "",                                  // Description
              this,                                // Parent
              view,                                // View Kind
              value.integer1Transient              // Value
          },
          // Field struct1Transient
          struct1Transient{
              typeRegistry,                               // Type Registry
              ::Xsmp::Tests::Types::Uuid_SimpleStructure, // Type UUID
              "struct1Transient",                         // Name
              "",                                         // Description
              this,                                       // Parent
              view,                                       // View Kind
              value.struct1Transient                      // Value
          },
          // Field booleanOutput
          booleanOutput{
              typeRegistry,            // Type Registry
              ::Smp::Uuids::Uuid_Bool, // Type UUID
              "booleanOutput",         // Name
              "",                      // Description
              this,                    // Parent
              view,                    // View Kind
              value.booleanOutput      // Value
          },
          // Field char8Output
          char8Output{
              typeRegistry,             // Type Registry
              ::Smp::Uuids::Uuid_Char8, // Type UUID
              "char8Output",            // Name
              "",                       // Description
              this,                     // Parent
              view,                     // View Kind
              value.char8Output         // Value
          },
          // Field enum1Output
          enum1Output{
              typeRegistry,                     // Type Registry
              ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
              "enum1Output",                    // Name
              "",                               // Description
              this,                             // Parent
              view,                             // View Kind
              value.enum1Output                 // Value
          },
          // Field string1Output
          string1Output{
              typeRegistry,                       // Type Registry
              ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
              "string1Output",                    // Name
              "",                                 // Description
              this,                               // Parent
              view,                               // View Kind
              value.string1Output                 // Value
          },
          // Field float1Output
          float1Output{
              typeRegistry,                      // Type Registry
              ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
              "float1Output",                    // Name
              "",                                // Description
              this,                              // Parent
              view,                              // View Kind
              value.float1Output                 // Value
          },
          // Field integer1Output
          integer1Output{
              typeRegistry,                        // Type Registry
              ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
              "integer1Output",                    // Name
              "",                                  // Description
              this,                                // Parent
              view,                                // View Kind
              value.integer1Output                 // Value
          },
          // Field struct1Output
          struct1Output{
              typeRegistry,                               // Type Registry
              ::Xsmp::Tests::Types::Uuid_SimpleStructure, // Type UUID
              "struct1Output",                            // Name
              "",                                         // Description
              this,                                       // Parent
              view,                                       // View Kind
              value.struct1Output                         // Value
          },
          // Field booleanForcible
          booleanForcible{
              typeRegistry,            // Type Registry
              ::Smp::Uuids::Uuid_Bool, // Type UUID
              "booleanForcible",       // Name
              "",                      // Description
              this,                    // Parent
              view,                    // View Kind
              value.booleanForcible    // Value
          },
          // Field char8Forcible
          char8Forcible{
              typeRegistry,             // Type Registry
              ::Smp::Uuids::Uuid_Char8, // Type UUID
              "char8Forcible",          // Name
              "",                       // Description
              this,                     // Parent
              view,                     // View Kind
              value.char8Forcible       // Value
          },
          // Field enum1Forcible
          enum1Forcible{
              typeRegistry,                     // Type Registry
              ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
              "enum1Forcible",                  // Name
              "",                               // Description
              this,                             // Parent
              view,                             // View Kind
              value.enum1Forcible               // Value
          },
          // Field string1Forcible
          string1Forcible{
              typeRegistry,                       // Type Registry
              ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
              "string1Forcible",                  // Name
              "",                                 // Description
              this,                               // Parent
              view,                               // View Kind
              value.string1Forcible               // Value
          },
          // Field float1Forcible
          float1Forcible{
              typeRegistry,                      // Type Registry
              ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
              "float1Forcible",                  // Name
              "",                                // Description
              this,                              // Parent
              view,                              // View Kind
              value.float1Forcible               // Value
          },
          // Field integer1Forcible
          integer1Forcible{
              typeRegistry,                        // Type Registry
              ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
              "integer1Forcible",                  // Name
              "",                                  // Description
              this,                                // Parent
              view,                                // View Kind
              value.integer1Forcible               // Value
          },
          // Field struct1Forcible
          struct1Forcible{
              typeRegistry,                               // Type Registry
              ::Xsmp::Tests::Types::Uuid_SimpleStructure, // Type UUID
              "struct1Forcible",                          // Name
              "",                                         // Description
              this,                                       // Parent
              view,                                       // View Kind
              value.struct1Forcible                       // Value
          },
          // Field booleanFailure
          booleanFailure{
              typeRegistry,            // Type Registry
              ::Smp::Uuids::Uuid_Bool, // Type UUID
              "booleanFailure",        // Name
              "",                      // Description
              this,                    // Parent
              view,                    // View Kind
              value.booleanFailure     // Value
          },
          // Field char8Failure
          char8Failure{
              typeRegistry,             // Type Registry
              ::Smp::Uuids::Uuid_Char8, // Type UUID
              "char8Failure",           // Name
              "",                       // Description
              this,                     // Parent
              view,                     // View Kind
              value.char8Failure        // Value
          },
          // Field enum1Failure
          enum1Failure{
              typeRegistry,                     // Type Registry
              ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
              "enum1Failure",                   // Name
              "",                               // Description
              this,                             // Parent
              view,                             // View Kind
              value.enum1Failure                // Value
          },
          // Field string1Failure
          string1Failure{
              typeRegistry,                       // Type Registry
              ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
              "string1Failure",                   // Name
              "",                                 // Description
              this,                               // Parent
              view,                               // View Kind
              value.string1Failure                // Value
          },
          // Field float1Failure
          float1Failure{
              typeRegistry,                      // Type Registry
              ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
              "float1Failure",                   // Name
              "",                                // Description
              this,                              // Parent
              view,                              // View Kind
              value.float1Failure                // Value
          },
          // Field integer1Failure
          integer1Failure{
              typeRegistry,                        // Type Registry
              ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
              "integer1Failure",                   // Name
              "",                                  // Description
              this,                                // Parent
              view,                                // View Kind
              value.integer1Failure                // Value
          },
          // Field struct1Failure
          struct1Failure{
              typeRegistry,                               // Type Registry
              ::Xsmp::Tests::Types::Uuid_SimpleStructure, // Type UUID
              "struct1Failure",                           // Name
              "",                                         // Description
              this,                                       // Parent
              view,                                       // View Kind
              value.struct1Failure                        // Value
          },
          // Field booleanAll
          booleanAll{
              typeRegistry,            // Type Registry
              ::Smp::Uuids::Uuid_Bool, // Type UUID
              "booleanAll",            // Name
              "",                      // Description
              this,                    // Parent
              view,                    // View Kind
              value.booleanAll         // Value
          },
          // Field char8All
          char8All{
              typeRegistry,             // Type Registry
              ::Smp::Uuids::Uuid_Char8, // Type UUID
              "char8All",               // Name
              "",                       // Description
              this,                     // Parent
              view,                     // View Kind
              value.char8All            // Value
          },
          // Field enum1All
          enum1All{
              typeRegistry,                     // Type Registry
              ::Xsmp::Tests::Types::Uuid_Enum1, // Type UUID
              "enum1All",                       // Name
              "",                               // Description
              this,                             // Parent
              view,                             // View Kind
              value.enum1All                    // Value
          },
          // Field string1All
          string1All{
              typeRegistry,                       // Type Registry
              ::Xsmp::Tests::Types::Uuid_String1, // Type UUID
              "string1All",                       // Name
              "",                                 // Description
              this,                               // Parent
              view,                               // View Kind
              value.string1All                    // Value
          },
          // Field float1All
          float1All{
              typeRegistry,                      // Type Registry
              ::Xsmp::Tests::Types::Uuid_Float1, // Type UUID
              "float1All",                       // Name
              "",                                // Description
              this,                              // Parent
              view,                              // View Kind
              value.float1All                    // Value
          },
          // Field integer1All
          integer1All{
              typeRegistry,                        // Type Registry
              ::Xsmp::Tests::Types::Uuid_Integer1, // Type UUID
              "integer1All",                       // Name
              "",                                  // Description
              this,                                // Parent
              view,                                // View Kind
              value.integer1All                    // Value
          },
          // Field struct1All
          struct1All{
              typeRegistry,                               // Type Registry
              ::Xsmp::Tests::Types::Uuid_SimpleStructure, // Type UUID
              "struct1All",                               // Name
              "",                                         // Description
              this,                                       // Parent
              view,                                       // View Kind
              value.struct1All                            // Value
          } {}
    _Field(const _Field &) = delete;
    _Field &operator=(const _Field &) = delete;

    // copy operator from ::Xsmp::Tests::Types::StructureWithCustomFields
    _Field &
    operator=(const ::Xsmp::Tests::Types::StructureWithCustomFields &other) {
      this->booleanInput = other.booleanInput;
      this->char8Input = other.char8Input;
      this->enum1Input = other.enum1Input;
      this->string1Input = other.string1Input;
      this->float1Input = other.float1Input;
      this->integer1Input = other.integer1Input;
      this->struct1Input = other.struct1Input;
      this->booleanTransient = other.booleanTransient;
      this->char8Transient = other.char8Transient;
      this->enum1Transient = other.enum1Transient;
      this->string1Transient = other.string1Transient;
      this->float1Transient = other.float1Transient;
      this->integer1Transient = other.integer1Transient;
      this->struct1Transient = other.struct1Transient;
      this->booleanOutput = other.booleanOutput;
      this->char8Output = other.char8Output;
      this->enum1Output = other.enum1Output;
      this->string1Output = other.string1Output;
      this->float1Output = other.float1Output;
      this->integer1Output = other.integer1Output;
      this->struct1Output = other.struct1Output;
      this->booleanForcible = other.booleanForcible;
      this->char8Forcible = other.char8Forcible;
      this->enum1Forcible = other.enum1Forcible;
      this->string1Forcible = other.string1Forcible;
      this->float1Forcible = other.float1Forcible;
      this->integer1Forcible = other.integer1Forcible;
      this->struct1Forcible = other.struct1Forcible;
      this->booleanFailure = other.booleanFailure;
      this->char8Failure = other.char8Failure;
      this->enum1Failure = other.enum1Failure;
      this->string1Failure = other.string1Failure;
      this->float1Failure = other.float1Failure;
      this->integer1Failure = other.integer1Failure;
      this->struct1Failure = other.struct1Failure;
      this->booleanAll = other.booleanAll;
      this->char8All = other.char8All;
      this->enum1All = other.enum1All;
      this->string1All = other.string1All;
      this->float1All = other.float1All;
      this->integer1All = other.integer1All;
      this->struct1All = other.struct1All;
      return *this;
    }

    // implicit convertion to ::Xsmp::Tests::Types::StructureWithCustomFields
    operator ::Xsmp::Tests::Types::StructureWithCustomFields() const noexcept {
      return {booleanInput,      char8Input,       enum1Input,
              string1Input,      float1Input,      integer1Input,
              struct1Input,      booleanTransient, char8Transient,
              enum1Transient,    string1Transient, float1Transient,
              integer1Transient, struct1Transient, booleanOutput,
              char8Output,       enum1Output,      string1Output,
              float1Output,      integer1Output,   struct1Output,
              booleanForcible,   char8Forcible,    enum1Forcible,
              string1Forcible,   float1Forcible,   integer1Forcible,
              struct1Forcible,   booleanFailure,   char8Failure,
              enum1Failure,      string1Failure,   float1Failure,
              integer1Failure,   struct1Failure,   booleanAll,
              char8All,          enum1All,         string1All,
              float1All,         integer1All,      struct1All};
    }

    // Fields declaration
    typename _BASE::template Field<::Smp::Bool>::input booleanInput;
    typename _BASE::template Field<::Smp::Char8>::input char8Input;
    typename _BASE::template Field<::Xsmp::Tests::Types::Enum1>::input
        enum1Input;
    typename _BASE::template Field<::Xsmp::Tests::Types::String1>::input
        string1Input;
    typename _BASE::template Field<::Xsmp::Tests::Types::Float1>::input
        float1Input;
    typename _BASE::template Field<::Xsmp::Tests::Types::Integer1>::input
        integer1Input;
    typename _BASE::template Field<::Xsmp::Tests::Types::SimpleStructure>::input
        struct1Input;
    typename _BASE::template Field<::Smp::Bool>::transient booleanTransient;
    typename _BASE::template Field<::Smp::Char8>::transient char8Transient;
    typename _BASE::template Field<::Xsmp::Tests::Types::Enum1>::transient
        enum1Transient;
    typename _BASE::template Field<::Xsmp::Tests::Types::String1>::transient
        string1Transient;
    typename _BASE::template Field<::Xsmp::Tests::Types::Float1>::transient
        float1Transient;
    typename _BASE::template Field<::Xsmp::Tests::Types::Integer1>::transient
        integer1Transient;
    typename _BASE::template Field<
        ::Xsmp::Tests::Types::SimpleStructure>::transient struct1Transient;
    typename _BASE::template Field<::Smp::Bool>::output booleanOutput;
    typename _BASE::template Field<::Smp::Char8>::output char8Output;
    typename _BASE::template Field<::Xsmp::Tests::Types::Enum1>::output
        enum1Output;
    typename _BASE::template Field<::Xsmp::Tests::Types::String1>::output
        string1Output;
    typename _BASE::template Field<::Xsmp::Tests::Types::Float1>::output
        float1Output;
    typename _BASE::template Field<::Xsmp::Tests::Types::Integer1>::output
        integer1Output;
    typename _BASE::template Field<
        ::Xsmp::Tests::Types::SimpleStructure>::output struct1Output;
    typename _BASE::template Field<::Smp::Bool>::forcible booleanForcible;
    typename _BASE::template Field<::Smp::Char8>::forcible char8Forcible;
    typename _BASE::template Field<::Xsmp::Tests::Types::Enum1>::forcible
        enum1Forcible;
    typename _BASE::template Field<::Xsmp::Tests::Types::String1>::forcible
        string1Forcible;
    typename _BASE::template Field<::Xsmp::Tests::Types::Float1>::forcible
        float1Forcible;
    typename _BASE::template Field<::Xsmp::Tests::Types::Integer1>::forcible
        integer1Forcible;
    typename _BASE::template Field<
        ::Xsmp::Tests::Types::SimpleStructure>::forcible struct1Forcible;
    typename _BASE::template Field<::Smp::Bool>::failure booleanFailure;
    typename _BASE::template Field<::Smp::Char8>::failure char8Failure;
    typename _BASE::template Field<::Xsmp::Tests::Types::Enum1>::failure
        enum1Failure;
    typename _BASE::template Field<::Xsmp::Tests::Types::String1>::failure
        string1Failure;
    typename _BASE::template Field<::Xsmp::Tests::Types::Float1>::failure
        float1Failure;
    typename _BASE::template Field<::Xsmp::Tests::Types::Integer1>::failure
        integer1Failure;
    typename _BASE::template Field<
        ::Xsmp::Tests::Types::SimpleStructure>::failure struct1Failure;
    typename _BASE::template Field<
        ::Smp::Bool>::transient::input::output::forcible::failure booleanAll;
    typename _BASE::template Field<
        ::Smp::Char8>::transient::input::output::forcible::failure char8All;
    typename _BASE::template Field<::Xsmp::Tests::Types::Enum1>::transient::
        input::output::forcible::failure enum1All;
    typename _BASE::template Field<::Xsmp::Tests::Types::String1>::transient::
        input::output::forcible::failure string1All;
    typename _BASE::template Field<::Xsmp::Tests::Types::Float1>::transient::
        input::output::forcible::failure float1All;
    typename _BASE::template Field<::Xsmp::Tests::Types::Integer1>::transient::
        input::output::forcible::failure integer1All;
    typename _BASE::template Field<::Xsmp::Tests::Types::SimpleStructure>::
        transient::input::output::forcible::failure struct1All;
  };
};

/// Universally unique identifier of type StructureWithCustomFields.
inline constexpr ::Smp::Uuid Uuid_StructureWithCustomFields{
    0xf7de138dU, 0xe0a5U, 0x4ae2U, 0x9624U, 0xab49cc75b8b8U};
} // namespace Xsmp::Tests::Types

#endif // XSMP_TESTS_TYPES_STRUCTUREWITHCUSTOMFIELDS_H_
