// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : ModelWithSimpleArrayFieldsGen.cpp
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/ModelWithSimpleArrayFieldsGen.cpp
// This file is auto-generated, Do not edit otherwise your changes will be lost

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/ViewKind.h>
#include <Xsmp/ComponentHelper.h>
#include <Xsmp/Tests/ModelWithSimpleArrayFields.h>

namespace Xsmp::Tests {
//--------------------------- Constructor -------------------------
ModelWithSimpleArrayFieldsGen::ModelWithSimpleArrayFieldsGen(
    ::Smp::String8 name, ::Smp::String8 description, ::Smp::IComposite *parent,
    ::Smp::ISimulator *simulator)
    : // Base class
      ::Xsmp::Model(name, description, parent, simulator),
      // Field boolean
      boolean{},
      // Field char8
      char8{},
      // Field enum1
      enum1{},
      // Field string1
      string1{},
      // Field float1
      float1{},
      // Field integer1
      integer1{},
      // Field booleanInput
      booleanInput{},
      // Field char8Input
      char8Input{},
      // Field enum1Input
      enum1Input{},
      // Field string1Input
      string1Input{},
      // Field float1Input
      float1Input{},
      // Field integer1Input
      integer1Input{},
      // Field booleanTransient
      booleanTransient{},
      // Field char8Transient
      char8Transient{},
      // Field enum1Transient
      enum1Transient{},
      // Field string1Transient
      string1Transient{},
      // Field float1Transient
      float1Transient{},
      // Field integer1Transient
      integer1Transient{},
      // Field booleanOutput
      booleanOutput{
          simulator->GetTypeRegistry(),               // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleBoolArray, // Type UUID
          "booleanOutput",                            // Name
          "",                                         // Description
          this,                                       // Parent
          ::Smp::ViewKind::VK_All                     // View Kind
      },
      // Field char8Output
      char8Output{
          simulator->GetTypeRegistry(),                // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleChar8Array, // Type UUID
          "char8Output",                               // Name
          "",                                          // Description
          this,                                        // Parent
          ::Smp::ViewKind::VK_All                      // View Kind
      },
      // Field enum1Output
      enum1Output{
          simulator->GetTypeRegistry(),                // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleEnum1Array, // Type UUID
          "enum1Output",                               // Name
          "",                                          // Description
          this,                                        // Parent
          ::Smp::ViewKind::VK_All                      // View Kind
      },
      // Field string1Output
      string1Output{
          simulator->GetTypeRegistry(),                  // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleString1Array, // Type UUID
          "string1Output",                               // Name
          "",                                            // Description
          this,                                          // Parent
          ::Smp::ViewKind::VK_All                        // View Kind
      },
      // Field float1Output
      float1Output{
          simulator->GetTypeRegistry(),                 // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleFloat1Array, // Type UUID
          "float1Output",                               // Name
          "",                                           // Description
          this,                                         // Parent
          ::Smp::ViewKind::VK_All                       // View Kind
      },
      // Field integer1Output
      integer1Output{
          simulator->GetTypeRegistry(),                   // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleInteger1Array, // Type UUID
          "integer1Output",                               // Name
          "",                                             // Description
          this,                                           // Parent
          ::Smp::ViewKind::VK_All                         // View Kind
      },
      // Field booleanFailure
      booleanFailure{
          simulator->GetTypeRegistry(),               // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleBoolArray, // Type UUID
          "booleanFailure",                           // Name
          "",                                         // Description
          this,                                       // Parent
          ::Smp::ViewKind::VK_All                     // View Kind
      },
      // Field char8Failure
      char8Failure{
          simulator->GetTypeRegistry(),                // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleChar8Array, // Type UUID
          "char8Failure",                              // Name
          "",                                          // Description
          this,                                        // Parent
          ::Smp::ViewKind::VK_All                      // View Kind
      },
      // Field enum1Failure
      enum1Failure{
          simulator->GetTypeRegistry(),                // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleEnum1Array, // Type UUID
          "enum1Failure",                              // Name
          "",                                          // Description
          this,                                        // Parent
          ::Smp::ViewKind::VK_All                      // View Kind
      },
      // Field string1Failure
      string1Failure{
          simulator->GetTypeRegistry(),                  // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleString1Array, // Type UUID
          "string1Failure",                              // Name
          "",                                            // Description
          this,                                          // Parent
          ::Smp::ViewKind::VK_All                        // View Kind
      },
      // Field float1Failure
      float1Failure{
          simulator->GetTypeRegistry(),                 // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleFloat1Array, // Type UUID
          "float1Failure",                              // Name
          "",                                           // Description
          this,                                         // Parent
          ::Smp::ViewKind::VK_All                       // View Kind
      },
      // Field integer1Failure
      integer1Failure{
          simulator->GetTypeRegistry(),                   // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleInteger1Array, // Type UUID
          "integer1Failure",                              // Name
          "",                                             // Description
          this,                                           // Parent
          ::Smp::ViewKind::VK_All                         // View Kind
      },
      // Field booleanAll
      booleanAll{
          simulator->GetTypeRegistry(),               // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleBoolArray, // Type UUID
          "booleanAll",                               // Name
          "",                                         // Description
          this,                                       // Parent
          ::Smp::ViewKind::VK_All                     // View Kind
      },
      // Field char8All
      char8All{
          simulator->GetTypeRegistry(),                // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleChar8Array, // Type UUID
          "char8All",                                  // Name
          "",                                          // Description
          this,                                        // Parent
          ::Smp::ViewKind::VK_All                      // View Kind
      },
      // Field enum1All
      enum1All{
          simulator->GetTypeRegistry(),                // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleEnum1Array, // Type UUID
          "enum1All",                                  // Name
          "",                                          // Description
          this,                                        // Parent
          ::Smp::ViewKind::VK_All                      // View Kind
      },
      // Field string1All
      string1All{
          simulator->GetTypeRegistry(),                  // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleString1Array, // Type UUID
          "string1All",                                  // Name
          "",                                            // Description
          this,                                          // Parent
          ::Smp::ViewKind::VK_All                        // View Kind
      },
      // Field float1All
      float1All{
          simulator->GetTypeRegistry(),                 // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleFloat1Array, // Type UUID
          "float1All",                                  // Name
          "",                                           // Description
          this,                                         // Parent
          ::Smp::ViewKind::VK_All                       // View Kind
      },
      // Field integer1All
      integer1All{
          simulator->GetTypeRegistry(),                   // Type Registry
          ::Xsmp::Tests::Types::Uuid_SimpleInteger1Array, // Type UUID
          "integer1All",                                  // Name
          "",                                             // Description
          this,                                           // Parent
          ::Smp::ViewKind::VK_All                         // View Kind
      } {}

void ModelWithSimpleArrayFieldsGen::Publish(::Smp::IPublication *receiver) {
  // Call parent class implementation first
  ::Xsmp::Model::Publish(receiver);

  // Publish field boolean
  receiver->PublishField(
      "boolean",                                  // Name
      "",                                         // Description
      &boolean,                                   // Address
      ::Xsmp::Tests::Types::Uuid_SimpleBoolArray, // Type UUID
      ::Smp::ViewKind::VK_All,                    // View Kind
      true,                                       // State
      false,                                      // Input
      false                                       // Output
  );
  // Publish field char8
  receiver->PublishField(
      "char8",                                     // Name
      "",                                          // Description
      &char8,                                      // Address
      ::Xsmp::Tests::Types::Uuid_SimpleChar8Array, // Type UUID
      ::Smp::ViewKind::VK_All,                     // View Kind
      true,                                        // State
      false,                                       // Input
      false                                        // Output
  );
  // Publish field enum1
  receiver->PublishField(
      "enum1",                                     // Name
      "",                                          // Description
      &enum1,                                      // Address
      ::Xsmp::Tests::Types::Uuid_SimpleEnum1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                     // View Kind
      true,                                        // State
      false,                                       // Input
      false                                        // Output
  );
  // Publish field string1
  receiver->PublishField(
      "string1",                                     // Name
      "",                                            // Description
      &string1,                                      // Address
      ::Xsmp::Tests::Types::Uuid_SimpleString1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                       // View Kind
      true,                                          // State
      false,                                         // Input
      false                                          // Output
  );
  // Publish field float1
  receiver->PublishField(
      "float1",                                     // Name
      "",                                           // Description
      &float1,                                      // Address
      ::Xsmp::Tests::Types::Uuid_SimpleFloat1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                      // View Kind
      true,                                         // State
      false,                                        // Input
      false                                         // Output
  );
  // Publish field integer1
  receiver->PublishField(
      "integer1",                                     // Name
      "",                                             // Description
      &integer1,                                      // Address
      ::Xsmp::Tests::Types::Uuid_SimpleInteger1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                        // View Kind
      true,                                           // State
      false,                                          // Input
      false                                           // Output
  );
  // Publish field booleanInput
  receiver->PublishField(
      "booleanInput",                             // Name
      "",                                         // Description
      &booleanInput,                              // Address
      ::Xsmp::Tests::Types::Uuid_SimpleBoolArray, // Type UUID
      ::Smp::ViewKind::VK_All,                    // View Kind
      true,                                       // State
      true,                                       // Input
      false                                       // Output
  );
  // Publish field char8Input
  receiver->PublishField(
      "char8Input",                                // Name
      "",                                          // Description
      &char8Input,                                 // Address
      ::Xsmp::Tests::Types::Uuid_SimpleChar8Array, // Type UUID
      ::Smp::ViewKind::VK_All,                     // View Kind
      true,                                        // State
      true,                                        // Input
      false                                        // Output
  );
  // Publish field enum1Input
  receiver->PublishField(
      "enum1Input",                                // Name
      "",                                          // Description
      &enum1Input,                                 // Address
      ::Xsmp::Tests::Types::Uuid_SimpleEnum1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                     // View Kind
      true,                                        // State
      true,                                        // Input
      false                                        // Output
  );
  // Publish field string1Input
  receiver->PublishField(
      "string1Input",                                // Name
      "",                                            // Description
      &string1Input,                                 // Address
      ::Xsmp::Tests::Types::Uuid_SimpleString1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                       // View Kind
      true,                                          // State
      true,                                          // Input
      false                                          // Output
  );
  // Publish field float1Input
  receiver->PublishField(
      "float1Input",                                // Name
      "",                                           // Description
      &float1Input,                                 // Address
      ::Xsmp::Tests::Types::Uuid_SimpleFloat1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                      // View Kind
      true,                                         // State
      true,                                         // Input
      false                                         // Output
  );
  // Publish field integer1Input
  receiver->PublishField(
      "integer1Input",                                // Name
      "",                                             // Description
      &integer1Input,                                 // Address
      ::Xsmp::Tests::Types::Uuid_SimpleInteger1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                        // View Kind
      true,                                           // State
      true,                                           // Input
      false                                           // Output
  );
  // Publish field booleanTransient
  receiver->PublishField(
      "booleanTransient",                         // Name
      "",                                         // Description
      &booleanTransient,                          // Address
      ::Xsmp::Tests::Types::Uuid_SimpleBoolArray, // Type UUID
      ::Smp::ViewKind::VK_All,                    // View Kind
      false,                                      // State
      false,                                      // Input
      false                                       // Output
  );
  // Publish field char8Transient
  receiver->PublishField(
      "char8Transient",                            // Name
      "",                                          // Description
      &char8Transient,                             // Address
      ::Xsmp::Tests::Types::Uuid_SimpleChar8Array, // Type UUID
      ::Smp::ViewKind::VK_All,                     // View Kind
      false,                                       // State
      false,                                       // Input
      false                                        // Output
  );
  // Publish field enum1Transient
  receiver->PublishField(
      "enum1Transient",                            // Name
      "",                                          // Description
      &enum1Transient,                             // Address
      ::Xsmp::Tests::Types::Uuid_SimpleEnum1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                     // View Kind
      false,                                       // State
      false,                                       // Input
      false                                        // Output
  );
  // Publish field string1Transient
  receiver->PublishField(
      "string1Transient",                            // Name
      "",                                            // Description
      &string1Transient,                             // Address
      ::Xsmp::Tests::Types::Uuid_SimpleString1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                       // View Kind
      false,                                         // State
      false,                                         // Input
      false                                          // Output
  );
  // Publish field float1Transient
  receiver->PublishField(
      "float1Transient",                            // Name
      "",                                           // Description
      &float1Transient,                             // Address
      ::Xsmp::Tests::Types::Uuid_SimpleFloat1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                      // View Kind
      false,                                        // State
      false,                                        // Input
      false                                         // Output
  );
  // Publish field integer1Transient
  receiver->PublishField(
      "integer1Transient",                            // Name
      "",                                             // Description
      &integer1Transient,                             // Address
      ::Xsmp::Tests::Types::Uuid_SimpleInteger1Array, // Type UUID
      ::Smp::ViewKind::VK_All,                        // View Kind
      false,                                          // State
      false,                                          // Input
      false                                           // Output
  );
  // Publish field booleanOutput
  receiver->PublishField(&booleanOutput);
  // Publish field char8Output
  receiver->PublishField(&char8Output);
  // Publish field enum1Output
  receiver->PublishField(&enum1Output);
  // Publish field string1Output
  receiver->PublishField(&string1Output);
  // Publish field float1Output
  receiver->PublishField(&float1Output);
  // Publish field integer1Output
  receiver->PublishField(&integer1Output);
  // Publish field booleanFailure
  receiver->PublishField(&booleanFailure);
  // Publish field char8Failure
  receiver->PublishField(&char8Failure);
  // Publish field enum1Failure
  receiver->PublishField(&enum1Failure);
  // Publish field string1Failure
  receiver->PublishField(&string1Failure);
  // Publish field float1Failure
  receiver->PublishField(&float1Failure);
  // Publish field integer1Failure
  receiver->PublishField(&integer1Failure);
  // Publish field booleanAll
  receiver->PublishField(&booleanAll);
  // Publish field char8All
  receiver->PublishField(&char8All);
  // Publish field enum1All
  receiver->PublishField(&enum1All);
  // Publish field string1All
  receiver->PublishField(&string1All);
  // Publish field float1All
  receiver->PublishField(&float1All);
  // Publish field integer1All
  receiver->PublishField(&integer1All);
  // Call user DoPublish if any
  ::Xsmp::Component::Helper::Publish<::Xsmp::Tests::ModelWithSimpleArrayFields>(
      this, receiver);
}

void ModelWithSimpleArrayFieldsGen::Configure(
    ::Smp::Services::ILogger *logger,
    ::Smp::Services::ILinkRegistry *linkRegistry) {
  // Call parent implementation first
  ::Xsmp::Model::Configure(logger, linkRegistry);

  // Call user DoConfigure if any
  ::Xsmp::Component::Helper::Configure<
      ::Xsmp::Tests::ModelWithSimpleArrayFields>(this, logger, linkRegistry);
}

void ModelWithSimpleArrayFieldsGen::Connect(::Smp::ISimulator *simulator) {
  // Call parent implementation first
  ::Xsmp::Model::Connect(simulator);

  // Call user DoConnect if any
  ::Xsmp::Component::Helper::Connect<::Xsmp::Tests::ModelWithSimpleArrayFields>(
      this, simulator);
}

void ModelWithSimpleArrayFieldsGen::Disconnect() {
  if (this->::Xsmp::Component::GetState() ==
      ::Smp::ComponentStateKind::CSK_Connected) {
    // Call user DoDisconnect if any
    ::Xsmp::Component::Helper::Disconnect<
        ::Xsmp::Tests::ModelWithSimpleArrayFields>(this);
  }

  // Call parent implementation last, to remove references to the Simulator and
  // its services
  ::Xsmp::Model::Disconnect();
}

const ::Smp::Uuid &ModelWithSimpleArrayFieldsGen::GetUuid() const {
  return Uuid_ModelWithSimpleArrayFields;
}

} // namespace Xsmp::Tests