// Copyright 2023-2026 THALES ALENIA SPACE FRANCE. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------
// File Name    : ModelWithArrayFieldsGen.h
// Generated by : XsmpSdkGenerator-2.0.2
// -----------------------------------------------------------------------------
/// @file Xsmp/Tests/ModelWithArrayFieldsGen.h
// This file is auto-generated, Do not edit otherwise your changes will be lost

#ifndef XSMP_TESTS_MODELWITHARRAYFIELDSGEN_H_
#define XSMP_TESTS_MODELWITHARRAYFIELDSGEN_H_

// ----------------------------------------------------------------------------
// --------------------------- Forward Declarations ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Tests {
class ModelWithArrayFields;
} // namespace Xsmp::Tests

// ----------------------------------------------------------------------------
// --------------------------- Include Header Files ---------------------------
// ----------------------------------------------------------------------------

#include <Smp/IComposite.h>
#include <Smp/ISimulator.h>
#include <Smp/PrimitiveTypes.h>
#include <Smp/Publication/ITypeRegistry.h>
#include <Xsmp/FallibleModel.h>
#include <Xsmp/Field.h>
#include <Xsmp/Model.h>
#include <Xsmp/Tests/Types/BoolArray.h>
#include <Xsmp/Tests/Types/Char8Array.h>
#include <Xsmp/Tests/Types/Enum1Array.h>
#include <Xsmp/Tests/Types/Float1Array.h>
#include <Xsmp/Tests/Types/Integer1Array.h>
#include <Xsmp/Tests/Types/String1Array.h>

// ----------------------------------------------------------------------------
// --------------------------- Types and Interfaces ---------------------------
// ----------------------------------------------------------------------------

namespace Xsmp::Tests {
/// Universally unique identifier of type ModelWithArrayFields.
inline constexpr ::Smp::Uuid Uuid_ModelWithArrayFields{
    0x120f3848U, 0x02d8U, 0x4cecU, 0xa0c2U, 0x32e3e5714e1aU};

class ModelWithArrayFieldsGen : public ::Xsmp::Model,
                                public virtual ::Xsmp::FallibleModel {
  friend class ::Xsmp::Tests::ModelWithArrayFields;

public:
  /// Constructor setting name, description, parent and simulator.
  /// @param name Name of new Model instance.
  /// @param description Description of new Model instance.
  /// @param parent Parent of new Model instance.
  /// @param simulator The simulator instance.
  ModelWithArrayFieldsGen(::Smp::String8 name, ::Smp::String8 description,
                          ::Smp::IComposite *parent,
                          ::Smp::ISimulator *simulator);
  /// deleted copy constructor
  ModelWithArrayFieldsGen(const ModelWithArrayFieldsGen &) = delete;
  /// deleted move constructor
  ModelWithArrayFieldsGen(ModelWithArrayFieldsGen &&) = delete;
  /// deleted copy assignment
  ModelWithArrayFieldsGen &operator=(const ModelWithArrayFieldsGen &) = delete;
  /// deleted move assignment
  ModelWithArrayFieldsGen &operator=(ModelWithArrayFieldsGen &&) = delete;

  /// Virtual destructor to release memory.
  ~ModelWithArrayFieldsGen() override = default;

  /// Request the Model to publish its fields, properties and
  /// operations against the provided publication receiver.
  /// @param   receiver Publication receiver.
  /// @throws  Smp::InvalidComponentState
  void Publish(::Smp::IPublication *receiver) override;

  /// Request the Model to perform any custom configuration. The
  /// component can create and configure other components using the field
  /// values of its published fields.
  /// @param   logger Logger service for logging of error messages during
  ///          configuration.
  /// @param   linkRegistry Reference to the link registry services, so
  ///          that the Model can register links that it creates
  ///          during configuration.
  /// @throws  Smp::InvalidComponentState
  void Configure(::Smp::Services::ILogger *logger,
                 ::Smp::Services::ILinkRegistry *linkRegistry) override;

  /// Allow the Model to connect to the simulator and its simulation
  /// services.
  /// @param   simulator Simulation Environment that hosts the Model.
  /// @throws  Smp::InvalidComponentState
  void Connect(::Smp::ISimulator *simulator) override;

  /// Ask the Model to disconnect from the simulator and all its
  /// simulation services.
  /// @throws  Smp::InvalidComponentState
  void Disconnect() override;

  /// Get Universally Unique Identifier of the Model.
  /// @return  Universally Unique Identifier of the Model.
  const ::Smp::Uuid &GetUuid() const override;

private:
  ::Xsmp::Tests::Types::BoolArray boolean;
  ::Xsmp::Tests::Types::Char8Array char8;
  ::Xsmp::Tests::Types::Enum1Array enum1;
  ::Xsmp::Tests::Types::String1Array string1;
  ::Xsmp::Tests::Types::Float1Array float1;
  ::Xsmp::Tests::Types::Integer1Array integer1;
  ::Xsmp::Tests::Types::BoolArray booleanInput;
  ::Xsmp::Tests::Types::Char8Array char8Input;
  ::Xsmp::Tests::Types::Enum1Array enum1Input;
  ::Xsmp::Tests::Types::String1Array string1Input;
  ::Xsmp::Tests::Types::Float1Array float1Input;
  ::Xsmp::Tests::Types::Integer1Array integer1Input;
  ::Xsmp::Tests::Types::BoolArray booleanTransient;
  ::Xsmp::Tests::Types::Char8Array char8Transient;
  ::Xsmp::Tests::Types::Enum1Array enum1Transient;
  ::Xsmp::Tests::Types::String1Array string1Transient;
  ::Xsmp::Tests::Types::Float1Array float1Transient;
  ::Xsmp::Tests::Types::Integer1Array integer1Transient;
  ::Xsmp::Field<::Xsmp::Tests::Types::BoolArray>::output booleanOutput;
  ::Xsmp::Field<::Xsmp::Tests::Types::Char8Array>::output char8Output;
  ::Xsmp::Field<::Xsmp::Tests::Types::Enum1Array>::output enum1Output;
  ::Xsmp::Field<::Xsmp::Tests::Types::String1Array>::output string1Output;
  ::Xsmp::Field<::Xsmp::Tests::Types::Float1Array>::output float1Output;
  ::Xsmp::Field<::Xsmp::Tests::Types::Integer1Array>::output integer1Output;
  ::Xsmp::Field<::Xsmp::Tests::Types::BoolArray>::forcible booleanForcible;
  ::Xsmp::Field<::Xsmp::Tests::Types::Char8Array>::forcible char8Forcible;
  ::Xsmp::Field<::Xsmp::Tests::Types::Enum1Array>::forcible enum1Forcible;
  ::Xsmp::Field<::Xsmp::Tests::Types::String1Array>::forcible string1Forcible;
  ::Xsmp::Field<::Xsmp::Tests::Types::Float1Array>::forcible float1Forcible;
  ::Xsmp::Field<::Xsmp::Tests::Types::Integer1Array>::forcible integer1Forcible;
  ::Xsmp::Field<::Xsmp::Tests::Types::BoolArray>::failure booleanFailure;
  ::Xsmp::Field<::Xsmp::Tests::Types::Char8Array>::failure char8Failure;
  ::Xsmp::Field<::Xsmp::Tests::Types::Enum1Array>::failure enum1Failure;
  ::Xsmp::Field<::Xsmp::Tests::Types::String1Array>::failure string1Failure;
  ::Xsmp::Field<::Xsmp::Tests::Types::Float1Array>::failure float1Failure;
  ::Xsmp::Field<::Xsmp::Tests::Types::Integer1Array>::failure integer1Failure;
  ::Xsmp::Field<::Xsmp::Tests::Types::BoolArray>::transient::input::output::
      forcible::failure booleanAll;
  ::Xsmp::Field<::Xsmp::Tests::Types::Char8Array>::transient::input::output::
      forcible::failure char8All;
  ::Xsmp::Field<::Xsmp::Tests::Types::Enum1Array>::transient::input::output::
      forcible::failure enum1All;
  ::Xsmp::Field<::Xsmp::Tests::Types::String1Array>::transient::input::output::
      forcible::failure string1All;
  ::Xsmp::Field<::Xsmp::Tests::Types::Float1Array>::transient::input::output::
      forcible::failure float1All;
  ::Xsmp::Field<::Xsmp::Tests::Types::Integer1Array>::transient::input::output::
      forcible::failure integer1All;
};
} // namespace Xsmp::Tests

#endif // XSMP_TESTS_MODELWITHARRAYFIELDSGEN_H_
